<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 5 Modelos no lineales | Notas de clase: Modelo lineal general II</title>
  <meta name="description" content="Capítulo 5 Modelos no lineales | Notas de clase: Modelo lineal general II" />
  <meta name="generator" content="bookdown 0.33 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 5 Modelos no lineales | Notas de clase: Modelo lineal general II" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 5 Modelos no lineales | Notas de clase: Modelo lineal general II" />
  
  
  

<meta name="author" content="Alvaro J. Flórez" />


<meta name="date" content="2023-10-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="selección-de-variables.html"/>
<link rel="next" href="modelo-lineal-generalizado.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Notas de clase MLGII</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introducción</a></li>
<li class="chapter" data-level="1" data-path="variables-indicadoras-o-dummies.html"><a href="variables-indicadoras-o-dummies.html"><i class="fa fa-check"></i><b>1</b> Variables indicadoras (o dummies)</a>
<ul>
<li class="chapter" data-level="1.1" data-path="variables-indicadoras-o-dummies.html"><a href="variables-indicadoras-o-dummies.html#ejemplos"><i class="fa fa-check"></i><b>1.1</b> Ejemplos</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="variables-indicadoras-o-dummies.html"><a href="variables-indicadoras-o-dummies.html#datos-de-atletas-australianos"><i class="fa fa-check"></i><b>1.1.1</b> Datos de atletas australianos</a></li>
<li class="chapter" data-level="1.1.2" data-path="variables-indicadoras-o-dummies.html"><a href="variables-indicadoras-o-dummies.html#datos-de-la-onu"><i class="fa fa-check"></i><b>1.1.2</b> Datos de la ONU</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="variables-indicadoras-o-dummies.html"><a href="variables-indicadoras-o-dummies.html#variables-indicadoras"><i class="fa fa-check"></i><b>1.2</b> Variables indicadoras</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="variables-indicadoras-o-dummies.html"><a href="variables-indicadoras-o-dummies.html#modelos-con-covariables-categóricas"><i class="fa fa-check"></i><b>1.2.1</b> Modelos con covariables categóricas</a></li>
<li class="chapter" data-level="1.2.2" data-path="variables-indicadoras-o-dummies.html"><a href="variables-indicadoras-o-dummies.html#modelo-para-los-datos-de-atletas-australianos"><i class="fa fa-check"></i><b>1.2.2</b> Modelo para los datos de atletas australianos</a></li>
<li class="chapter" data-level="1.2.3" data-path="variables-indicadoras-o-dummies.html"><a href="variables-indicadoras-o-dummies.html#modelo-para-los-datos-de-la-onu"><i class="fa fa-check"></i><b>1.2.3</b> Modelo para los datos de la ONU</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html"><i class="fa fa-check"></i><b>2</b> Modelos polinomiales</a>
<ul>
<li class="chapter" data-level="2.1" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#ejemplos-1"><i class="fa fa-check"></i><b>2.1</b> Ejemplos</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#pasteles"><i class="fa fa-check"></i><b>2.1.1</b> Pasteles</a></li>
<li class="chapter" data-level="2.1.2" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#datos-de-boston"><i class="fa fa-check"></i><b>2.1.2</b> Datos de Boston</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#modelos-polinomiales-1"><i class="fa fa-check"></i><b>2.2</b> Modelos polinomiales</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#interpretación-de-los-coeficientes"><i class="fa fa-check"></i><b>2.2.1</b> Interpretación de los coeficientes</a></li>
<li class="chapter" data-level="2.2.2" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#pasteles-1"><i class="fa fa-check"></i><b>2.2.2</b> Pasteles</a></li>
<li class="chapter" data-level="2.2.3" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#datos-de-boston-1"><i class="fa fa-check"></i><b>2.2.3</b> Datos de Boston</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#regresión-por-segmentos"><i class="fa fa-check"></i><b>2.3</b> Regresión por segmentos</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#ejemplo"><i class="fa fa-check"></i><b>2.3.1</b> Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multicolinealidad.html"><a href="multicolinealidad.html"><i class="fa fa-check"></i><b>3</b> Multicolinealidad</a>
<ul>
<li class="chapter" data-level="3.1" data-path="multicolinealidad.html"><a href="multicolinealidad.html#ejemplos-2"><i class="fa fa-check"></i><b>3.1</b> Ejemplos</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="multicolinealidad.html"><a href="multicolinealidad.html#cemento"><i class="fa fa-check"></i><b>3.1.1</b> Cemento</a></li>
<li class="chapter" data-level="3.1.2" data-path="multicolinealidad.html"><a href="multicolinealidad.html#grasa-corporal"><i class="fa fa-check"></i><b>3.1.2</b> Grasa corporal</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="multicolinealidad.html"><a href="multicolinealidad.html#multicolinealidad-1"><i class="fa fa-check"></i><b>3.2</b> Multicolinealidad</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="multicolinealidad.html"><a href="multicolinealidad.html#causas-de-la-multicolinealidad"><i class="fa fa-check"></i><b>3.2.1</b> Causas de la multicolinealidad</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="multicolinealidad.html"><a href="multicolinealidad.html#detección-de-multicolinealidad"><i class="fa fa-check"></i><b>3.3</b> Detección de multicolinealidad</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="multicolinealidad.html"><a href="multicolinealidad.html#factores-de-inflación-de-varianza"><i class="fa fa-check"></i><b>3.3.1</b> Factores de inflación de varianza</a></li>
<li class="chapter" data-level="3.3.2" data-path="multicolinealidad.html"><a href="multicolinealidad.html#valores-propios-de-boldsymbol-zboldsymbol-z"><i class="fa fa-check"></i><b>3.3.2</b> Valores propios de <span class="math inline">\(\boldsymbol Z&#39;\boldsymbol Z\)</span></a></li>
<li class="chapter" data-level="3.3.3" data-path="multicolinealidad.html"><a href="multicolinealidad.html#valores-singulares-de-boldsymbol-z"><i class="fa fa-check"></i><b>3.3.3</b> Valores singulares de <span class="math inline">\(\boldsymbol Z\)</span></a></li>
<li class="chapter" data-level="3.3.4" data-path="multicolinealidad.html"><a href="multicolinealidad.html#proporciones-de-descomposición-de-varianza"><i class="fa fa-check"></i><b>3.3.4</b> Proporciones de descomposición de varianza</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="multicolinealidad.html"><a href="multicolinealidad.html#datos-de-cemento"><i class="fa fa-check"></i><b>3.4</b> Datos de cemento</a></li>
<li class="chapter" data-level="3.5" data-path="multicolinealidad.html"><a href="multicolinealidad.html#datos-de-grasa-corporal"><i class="fa fa-check"></i><b>3.5</b> Datos de grasa corporal</a></li>
<li class="chapter" data-level="3.6" data-path="multicolinealidad.html"><a href="multicolinealidad.html#solución-al-problema-de-multicolinealidad"><i class="fa fa-check"></i><b>3.6</b> Solución al problema de multicolinealidad</a></li>
<li class="chapter" data-level="3.7" data-path="multicolinealidad.html"><a href="multicolinealidad.html#estimador-de-ridge"><i class="fa fa-check"></i><b>3.7</b> Estimador de ridge</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="multicolinealidad.html"><a href="multicolinealidad.html#datos-de-cemento-1"><i class="fa fa-check"></i><b>3.7.1</b> Datos de cemento</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="multicolinealidad.html"><a href="multicolinealidad.html#estimador-por-componentes-principales"><i class="fa fa-check"></i><b>3.8</b> Estimador por componentes principales</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="multicolinealidad.html"><a href="multicolinealidad.html#datos-de-cemento-2"><i class="fa fa-check"></i><b>3.8.1</b> Datos de cemento</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="selección-de-variables.html"><a href="selección-de-variables.html"><i class="fa fa-check"></i><b>4</b> Selección de variables</a>
<ul>
<li class="chapter" data-level="4.1" data-path="selección-de-variables.html"><a href="selección-de-variables.html#ejemplos-3"><i class="fa fa-check"></i><b>4.1</b> Ejemplos</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="selección-de-variables.html"><a href="selección-de-variables.html#unidad-quirúrgica"><i class="fa fa-check"></i><b>4.1.1</b> Unidad quirúrgica</a></li>
<li class="chapter" data-level="4.1.2" data-path="selección-de-variables.html"><a href="selección-de-variables.html#grasa-corporal-1"><i class="fa fa-check"></i><b>4.1.2</b> Grasa corporal</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="selección-de-variables.html"><a href="selección-de-variables.html#problema-de-selección-de-variables"><i class="fa fa-check"></i><b>4.2</b> Problema de selección de variables</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="selección-de-variables.html"><a href="selección-de-variables.html#qué-pasa-si-ignoramos-covariables-importantes"><i class="fa fa-check"></i><b>4.2.1</b> ¿Qué pasa si ignoramos covariables importantes?</a></li>
<li class="chapter" data-level="4.2.2" data-path="selección-de-variables.html"><a href="selección-de-variables.html#que-pasa-si-incluimos-covariables-irrelevantes"><i class="fa fa-check"></i><b>4.2.2</b> ¿Que pasa si incluimos covariables irrelevantes?</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="selección-de-variables.html"><a href="selección-de-variables.html#métodos-para-la-selección-de-variables"><i class="fa fa-check"></i><b>4.3</b> Métodos para la selección de variables</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="selección-de-variables.html"><a href="selección-de-variables.html#coeficiente-de-determinación"><i class="fa fa-check"></i><b>4.3.1</b> Coeficiente de determinación</a></li>
<li class="chapter" data-level="4.3.2" data-path="selección-de-variables.html"><a href="selección-de-variables.html#coeficiente-de-determinación-ajustado"><i class="fa fa-check"></i><b>4.3.2</b> Coeficiente de determinación ajustado</a></li>
<li class="chapter" data-level="4.3.3" data-path="selección-de-variables.html"><a href="selección-de-variables.html#c_p-de-mallows"><i class="fa fa-check"></i><b>4.3.3</b> C<span class="math inline">\(_p\)</span> de Mallows</a></li>
<li class="chapter" data-level="4.3.4" data-path="selección-de-variables.html"><a href="selección-de-variables.html#estadístico-press"><i class="fa fa-check"></i><b>4.3.4</b> Estadístico PRESS</a></li>
<li class="chapter" data-level="4.3.5" data-path="selección-de-variables.html"><a href="selección-de-variables.html#criterios-de-información"><i class="fa fa-check"></i><b>4.3.5</b> Criterios de información</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="selección-de-variables.html"><a href="selección-de-variables.html#comparación-de-los-modelos"><i class="fa fa-check"></i><b>4.4</b> Comparación de los modelos</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="selección-de-variables.html"><a href="selección-de-variables.html#todos-los-posibles-modelos"><i class="fa fa-check"></i><b>4.4.1</b> Todos los posibles modelos</a></li>
<li class="chapter" data-level="4.4.2" data-path="selección-de-variables.html"><a href="selección-de-variables.html#algorítmos-de-selección"><i class="fa fa-check"></i><b>4.4.2</b> Algorítmos de selección</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="selección-de-variables.html"><a href="selección-de-variables.html#regresión-de-lasso"><i class="fa fa-check"></i><b>4.5</b> Regresión de LASSO</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="selección-de-variables.html"><a href="selección-de-variables.html#datos-de-grasa-corporal-1"><i class="fa fa-check"></i><b>4.5.1</b> Datos de grasa corporal</a></li>
<li class="chapter" data-level="4.5.2" data-path="selección-de-variables.html"><a href="selección-de-variables.html#validación-cruzada"><i class="fa fa-check"></i><b>4.5.2</b> Validación cruzada</a></li>
<li class="chapter" data-level="4.5.3" data-path="selección-de-variables.html"><a href="selección-de-variables.html#ejemplo-grasa-corporal"><i class="fa fa-check"></i><b>4.5.3</b> Ejemplo grasa corporal</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html"><i class="fa fa-check"></i><b>5</b> Modelos no lineales</a>
<ul>
<li class="chapter" data-level="5.1" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#ejemplos-4"><i class="fa fa-check"></i><b>5.1</b> Ejemplos</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#crecimiento-de-pavos"><i class="fa fa-check"></i><b>5.1.1</b> Crecimiento de pavos</a></li>
<li class="chapter" data-level="5.1.2" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#puromicina"><i class="fa fa-check"></i><b>5.1.2</b> Puromicina</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#modelos-no-lineales-1"><i class="fa fa-check"></i><b>5.2</b> Modelos no lineales</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#modelos-no-lineales-linealizables"><i class="fa fa-check"></i><b>5.2.1</b> Modelos no-lineales linealizables</a></li>
<li class="chapter" data-level="5.2.2" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#estimación-de-los-parámetros"><i class="fa fa-check"></i><b>5.2.2</b> Estimación de los parámetros</a></li>
<li class="chapter" data-level="5.2.3" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#inferencia-sobre-los-parámetros"><i class="fa fa-check"></i><b>5.2.3</b> Inferencia sobre los parámetros</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#método-de-bootstrap"><i class="fa fa-check"></i><b>5.3</b> Método de Bootstrap</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#bootstrap-en-regresión"><i class="fa fa-check"></i><b>5.3.1</b> Bootstrap en regresión</a></li>
<li class="chapter" data-level="5.3.2" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#algunas-consideraciones"><i class="fa fa-check"></i><b>5.3.2</b> Algunas consideraciones</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html"><i class="fa fa-check"></i><b>6</b> Modelo lineal generalizado</a>
<ul>
<li class="chapter" data-level="6.1" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#introducción-1"><i class="fa fa-check"></i><b>6.1</b> Introducción</a></li>
<li class="chapter" data-level="6.2" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#casos-de-estudio"><i class="fa fa-check"></i><b>6.2</b> Casos de estudio</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#mortalidad-de-escarabajos"><i class="fa fa-check"></i><b>6.2.1</b> Mortalidad de escarabajos</a></li>
<li class="chapter" data-level="6.2.2" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#ataques-de-epilepsia"><i class="fa fa-check"></i><b>6.2.2</b> ataques de epilepsia</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#preambulo"><i class="fa fa-check"></i><b>6.3</b> Preambulo</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#familia-exponencial"><i class="fa fa-check"></i><b>6.3.1</b> Familia exponencial</a></li>
<li class="chapter" data-level="6.3.2" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#relación-media-varianza"><i class="fa fa-check"></i><b>6.3.2</b> Relación media-varianza:</a></li>
<li class="chapter" data-level="6.3.3" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#estimador-de-máxima-verosimilitud"><i class="fa fa-check"></i><b>6.3.3</b> Estimador de máxima verosimilitud</a></li>
<li class="chapter" data-level="6.3.4" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#métodos-iterativos-de-maximización"><i class="fa fa-check"></i><b>6.3.4</b> Métodos iterativos de maximización</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#modelo-lineal-generalizado-glm"><i class="fa fa-check"></i><b>6.4</b> Modelo lineal generalizado (GLM)</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#componente-aleatorio"><i class="fa fa-check"></i><b>6.4.1</b> Componente aleatorio</a></li>
<li class="chapter" data-level="6.4.2" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#predictor-lineal"><i class="fa fa-check"></i><b>6.4.2</b> Predictor lineal</a></li>
<li class="chapter" data-level="6.4.3" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#función-de-enlace"><i class="fa fa-check"></i><b>6.4.3</b> Función de enlace</a></li>
<li class="chapter" data-level="6.4.4" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#ejemplos-de-glm"><i class="fa fa-check"></i><b>6.4.4</b> Ejemplos de GLM</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#ajuste-de-un-glm"><i class="fa fa-check"></i><b>6.5</b> Ajuste de un GLM</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#especificación-del-modelo"><i class="fa fa-check"></i><b>6.5.1</b> Especificación del modelo</a></li>
<li class="chapter" data-level="6.5.2" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#estimador-por-máxima-verosimilitud-para-boldsymbol-beta"><i class="fa fa-check"></i><b>6.5.2</b> Estimador por máxima verosimilitud para <span class="math inline">\(\boldsymbol \beta\)</span></a></li>
<li class="chapter" data-level="6.5.3" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#interpretación-de-parámetros---modelo-logístico"><i class="fa fa-check"></i><b>6.5.3</b> interpretación de parámetros - modelo logístico</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#pruebas-de-hipótesis"><i class="fa fa-check"></i><b>6.6</b> Pruebas de hipótesis</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#método-de-razón-de-verosimilitud"><i class="fa fa-check"></i><b>6.6.1</b> Método de razón de verosimilitud</a></li>
<li class="chapter" data-level="6.6.2" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#método-de-wald"><i class="fa fa-check"></i><b>6.6.2</b> Método de Wald</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#intervalos-de-confianza"><i class="fa fa-check"></i><b>6.7</b> intervalos de confianza</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#intervalo-de-confianza-para-la-media"><i class="fa fa-check"></i><b>6.7.1</b> Intervalo de confianza para la media</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#devianza"><i class="fa fa-check"></i><b>6.8</b> Devianza</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#el-estadístico-chi-cuadrado-de-pearson"><i class="fa fa-check"></i><b>6.8.1</b> El estadístico chi-cuadrado de Pearson</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#bondad-de-ajuste"><i class="fa fa-check"></i><b>6.9</b> Bondad de ajuste</a></li>
<li class="chapter" data-level="6.10" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#selección-de-variables-1"><i class="fa fa-check"></i><b>6.10</b> Selección de variables</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="modelo-logístico.html"><a href="modelo-logístico.html"><i class="fa fa-check"></i><b>7</b> Modelo logístico</a>
<ul>
<li class="chapter" data-level="7.1" data-path="modelo-logístico.html"><a href="modelo-logístico.html#casos-de-estudio-1"><i class="fa fa-check"></i><b>7.1</b> Casos de estudio</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="modelo-logístico.html"><a href="modelo-logístico.html#mortalidad-de-escarabajos-1"><i class="fa fa-check"></i><b>7.1.1</b> Mortalidad de escarabajos</a></li>
<li class="chapter" data-level="7.1.2" data-path="modelo-logístico.html"><a href="modelo-logístico.html#bajo-peso-al-nacer"><i class="fa fa-check"></i><b>7.1.2</b> Bajo peso al nacer</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="modelo-logístico.html"><a href="modelo-logístico.html#datos-agrupados-o-datos-no-agrupados"><i class="fa fa-check"></i><b>7.2</b> Datos agrupados o datos no agrupados</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="modelo-logístico.html"><a href="modelo-logístico.html#datos-agrupados"><i class="fa fa-check"></i><b>7.2.1</b> Datos agrupados</a></li>
<li class="chapter" data-level="7.2.2" data-path="modelo-logístico.html"><a href="modelo-logístico.html#datos-no-agrupados"><i class="fa fa-check"></i><b>7.2.2</b> Datos no agrupados</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="modelo-logístico.html"><a href="modelo-logístico.html#funciones-de-enlace"><i class="fa fa-check"></i><b>7.3</b> Funciones de enlace</a></li>
<li class="chapter" data-level="7.4" data-path="modelo-logístico.html"><a href="modelo-logístico.html#curva-característica-operativa-del-receptorroc"><i class="fa fa-check"></i><b>7.4</b> Curva característica operativa del receptor(ROC)</a></li>
<li class="chapter" data-level="7.5" data-path="modelo-logístico.html"><a href="modelo-logístico.html#sobredispersión"><i class="fa fa-check"></i><b>7.5</b> Sobredispersión</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="modelo-logístico.html"><a href="modelo-logístico.html#evalaución-de-sobredispersión"><i class="fa fa-check"></i><b>7.5.1</b> Evalaución de sobredispersión</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="modelo-logístico.html"><a href="modelo-logístico.html#distribución-beta-binomial"><i class="fa fa-check"></i><b>7.6</b> Distribución beta-binomial</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="modelo-logístico.html"><a href="modelo-logístico.html#modelo-beta-binomial"><i class="fa fa-check"></i><b>7.6.1</b> Modelo beta-binomial</a></li>
<li class="chapter" data-level="7.6.2" data-path="modelo-logístico.html"><a href="modelo-logístico.html#estudio-de-teratología"><i class="fa fa-check"></i><b>7.6.2</b> Estudio de teratología</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html"><i class="fa fa-check"></i><b>8</b> Modelo para conteos</a>
<ul>
<li class="chapter" data-level="8.1" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#casos-de-estudio-2"><i class="fa fa-check"></i><b>8.1</b> Casos de estudio</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#ataques-de-epilepsia-1"><i class="fa fa-check"></i><b>8.1.1</b> Ataques de epilepsia</a></li>
<li class="chapter" data-level="8.1.2" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#muertes-por-enfermedades-cardiovasculares-en-doctores-del-reino-unido"><i class="fa fa-check"></i><b>8.1.2</b> Muertes por enfermedades cardiovasculares en doctores del Reino Unido</a></li>
<li class="chapter" data-level="8.1.3" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#número-de-cangrejos-satélites"><i class="fa fa-check"></i><b>8.1.3</b> Número de cangrejos satélites</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#modelo-poisson"><i class="fa fa-check"></i><b>8.2</b> Modelo Poisson</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#modelo-de-conteo-con-offset"><i class="fa fa-check"></i><b>8.2.1</b> Modelo de conteo con offset</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#sobredispersión-1"><i class="fa fa-check"></i><b>8.3</b> Sobredispersión</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#distribución-binomial-negativa"><i class="fa fa-check"></i><b>8.3.1</b> Distribución binomial negativa</a></li>
<li class="chapter" data-level="8.3.2" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#modelo-binomial-negativo-poisson-gamma"><i class="fa fa-check"></i><b>8.3.2</b> Modelo binomial negativo (Poisson-gamma)</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#inflación-de-ceros"><i class="fa fa-check"></i><b>8.4</b> Inflación de ceros</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#modelo-de-inflación-de-ceros"><i class="fa fa-check"></i><b>8.4.1</b> Modelo de inflación de ceros</a></li>
<li class="chapter" data-level="8.4.2" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#modelo-hurdle"><i class="fa fa-check"></i><b>8.4.2</b> Modelo Hurdle</a></li>
<li class="chapter" data-level="8.4.3" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#número-de-cangrejos-satélites-1"><i class="fa fa-check"></i><b>8.4.3</b> Número de cangrejos satélites</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html"><i class="fa fa-check"></i><b>9</b> Modelo lineal mixto</a>
<ul>
<li class="chapter" data-level="9.1" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html#casos-de-estudio-3"><i class="fa fa-check"></i><b>9.1</b> Casos de estudio</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html#peso-al-nacer-de-ratas"><i class="fa fa-check"></i><b>9.1.1</b> Peso al nacer de ratas</a></li>
<li class="chapter" data-level="9.1.2" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html#capacidad-respiratoria"><i class="fa fa-check"></i><b>9.1.2</b> Capacidad respiratoria</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html#datos-por-cluster-correlacionados"><i class="fa fa-check"></i><b>9.2</b> Datos por cluster (correlacionados)</a></li>
<li class="chapter" data-level="9.3" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html#notación"><i class="fa fa-check"></i><b>9.3</b> Notación</a></li>
<li class="chapter" data-level="9.4" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html#modelos-con-intercepto-aleatorios"><i class="fa fa-check"></i><b>9.4</b> Modelos con intercepto aleatorios</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html#modelo-con-pendiente-aleatoria"><i class="fa fa-check"></i><b>9.4.1</b> Modelo con pendiente aleatoria</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html#modelo-lineal-mixto-1"><i class="fa fa-check"></i><b>9.5</b> Modelo lineal mixto</a></li>
<li class="chapter" data-level="9.6" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html#estimación-de-los-parámetros-1"><i class="fa fa-check"></i><b>9.6</b> Estimación de los parámetros</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html#estimación-del-modelo-con-intercepto-aleatorio"><i class="fa fa-check"></i><b>9.6.1</b> Estimación del modelo con intercepto aleatorio</a></li>
<li class="chapter" data-level="9.6.2" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html#estimación-del-modelo-con-pendiente-aleatoria"><i class="fa fa-check"></i><b>9.6.2</b> Estimación del modelo con pendiente aleatoria</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Notas de clase: Modelo lineal general II</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelos-no-lineales" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Capítulo 5</span> Modelos no lineales<a href="modelos-no-lineales.html#modelos-no-lineales" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="ejemplos-4" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Ejemplos<a href="modelos-no-lineales.html#ejemplos-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="crecimiento-de-pavos" class="section level3 hasAnchor" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Crecimiento de pavos<a href="modelos-no-lineales.html#crecimiento-de-pavos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Considere los datos de crecimiento de pavos (<code>data(turk0)</code>) de la librería <code>alr4</code>. A 60 corrales de pavos se les alimentó con una dieta similar, complementada con dosis de metionina diferente. Luego de un tiempo determnado, se observó el peso ganado por cada corral.</p>
<p>Las variables son:</p>
<ul>
<li><strong><code>A</code>:</strong> Cantidad de suplemento de metionina ( % de la dieta).</li>
<li><strong><code>Gain</code>:</strong> Peso medio ganado por corral (gramos) después de 3 semanas.</li>
</ul>
<p>El objetivo del estudio es evaluar la metionina como suplemento alimenticio para pavos. En la Figura <a href="modelos-no-lineales.html#fig:plotpavos">5.1</a> podemos observar que hay una relación positiva, a mayor cantidad de metionina, mayor peso ganado. Sin embargo, la relación no es lineal. Por lo que sería necesario hacer transformaciones sobre las variables o considerar modelos polinomiales para ajustar un modelo lineal a los datos. Otra alternativa es considerar modelos no lineales.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="modelos-no-lineales.html#cb95-1" tabindex="-1"></a><span class="fu">plot</span>(Gain<span class="sc">~</span>A,<span class="at">data=</span>turk0,<span class="at">xlab=</span><span class="st">&#39;cantidad de metionina (% dieta)&#39;</span>,<span class="at">ylab=</span><span class="st">&#39;Peso ganado por corral (gramos)&#39;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plotpavos"></span>
<img src="MLG2_files/figure-html/plotpavos-1.png" alt="Datos pavos. Relación entre el peso ganado por corral y el % de metionina en la dieta." width="768" />
<p class="caption">
Figure 5.1: Datos pavos. Relación entre el peso ganado por corral y el % de metionina en la dieta.
</p>
</div>
<p>Para estos datos se puede considerar el siguiente modelo de crecimiento:
<span class="math display">\[
E(Gain|A)=\theta_{1}+\theta_{2}[1-exp(-\theta_{3}A)]
\]</span>
Dado que este modelo no es una combinación lineal de los parámetros, <span class="math inline">\(\boldsymbol \theta= (\theta_1,\theta_2,\theta_3)\)</span>, se considera como un modelo lineal. Este modelo es comunmente utilizado para ajustar crecimiento dado que sus parámetros tienen interpretación:</p>
<ul>
<li>Si <span class="math inline">\(A=0\)</span>, entonces <span class="math inline">\(E(Gain|A)=\theta_{1}\)</span>. Es decir, <span class="math inline">\(\theta_{1}\)</span> determina el peso ganado medio sin suplemento de metionina.</li>
<li>Si <span class="math inline">\(\theta_{3}&gt;0\)</span>, <span class="math inline">\(\theta_{1}+\theta_{2}\)</span> es la asíntota. Es decir, la ganancia máxima de peso que se puede lograr.</li>
<li><span class="math inline">\(\theta_{2}\)</span> es el máximo crecimiento adicional debido al suplemento.</li>
<li><span class="math inline">\(\theta_{3}\)</span> representa la tasa de crecimiento. A valores de <span class="math inline">\(\theta_3\)</span> mas grandes, el crecimiento esperado se acerca a su máximo más rápidamente.</li>
</ul>
</div>
<div id="puromicina" class="section level3 hasAnchor" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> Puromicina<a href="modelos-no-lineales.html#puromicina" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Los datos <code>Puromycin</code> de la librería <code>datasets</code> contienen información de la reacción enzimática (qué tan rápido ésta cataliza la reacción que
convierte un sustrato en producto) de 23 encimas, donde 12 de ellas fueron tratadas con Puromicina (un antibiótico). Las variables son:</p>
<ul>
<li><code>conc</code> :concentración de sustrato (ppm).</li>
<li><code>rate</code>:velocidad de reacción instantáneas (conteo/min2)</li>
<li><code>state</code>:tratado y no tratado.</li>
</ul>
<p>El objetivo es evaluar la velocidad de reacción y el efecto de la Puromicina. La relación de la velocidad de reacción en función de la concentración de sustraro se puede observar en la Figura <a href="modelos-no-lineales.html#fig:plotpurom">5.2</a>.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="modelos-no-lineales.html#cb96-1" tabindex="-1"></a><span class="fu">plot</span>(Puromycin<span class="sc">$</span>conc,Puromycin<span class="sc">$</span>rate,<span class="at">col=</span>Puromycin<span class="sc">$</span>state,</span>
<span id="cb96-2"><a href="modelos-no-lineales.html#cb96-2" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;concentración de sustrato (ppm)&#39;</span>,</span>
<span id="cb96-3"><a href="modelos-no-lineales.html#cb96-3" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&#39;velocidad de reacción&#39;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plotpurom"></span>
<img src="MLG2_files/figure-html/plotpurom-1.png" alt="Daros Puromicina. Diagrama de dispersión: Relación entre la velocidad de reacción y la concentración de sustrato. Encimas tratadas(puntos negros), Encimas no tratadas(puntos rojos)" width="768" />
<p class="caption">
Figure 5.2: Daros Puromicina. Diagrama de dispersión: Relación entre la velocidad de reacción y la concentración de sustrato. Encimas tratadas(puntos negros), Encimas no tratadas(puntos rojos)
</p>
</div>
<p>Aquí vamos a considerar el modelo Michaelis-Menten (modelo comunmente utilizado en bioquímica):</p>
<p><span class="math display">\[
y_{i}=\frac{x_{1}\theta_{1}}{\theta_{2}+x_{1}}+\varepsilon_{i}.
\]</span>
En este caso, <span class="math inline">\(\theta_1\)</span> es la asíntota. Es decir la velocidad de reacción máxima. Mientras que <span class="math inline">\(\theta_2\)</span> determina la concentración en la cual se obtiene la mitad de la velocidad máxima. Esto lo podemos observar en la Figura <a href="modelos-no-lineales.html#fig:modMichMen">5.3</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:modMichMen"></span>
<img src="figs/Michaelis.jpg" alt="Modelo Michaelis-Menten" width="75%" />
<p class="caption">
Figure 5.3: Modelo Michaelis-Menten
</p>
</div>
<p>Dado que se tienen células tratadas y no tratadas, se propone el siguiente modelo:
<span class="math display">\[
rate_{i}=\frac{conc_{i}\theta_{1}+state_{i}conc_{i}\theta_{3}}
{\theta_{2}+state_{i}\theta_{3}+conc_{i}}+\varepsilon_{i}.
\]</span>
Por lo que se tiene una curva diferente para las enzimas tratadas y no tratadas:</p>
<ul>
<li>Para enzimas no tratadas:</li>
</ul>
<p><span class="math display">\[
E(rate_{i}|state=0)=\frac{conc_{i}\theta_{1}}{\theta_{2}+conc_{i}}.
\]</span></p>
<ul>
<li>Para enzimas tratadas:
<span class="math display">\[
E(rate_{i}|state=1)=\frac{conc_{i}(\theta_{1}+\theta_{3})}{(\theta_{2}+\theta_{4})+conc_{i}}.
\]</span>
Por lo que, <span class="math inline">\(\theta_3\)</span> determina la velocidad máxima entre las células tratadas y no las no tratadas. De igual forma, <span class="math inline">\(\theta_{4}\)</span> indica la diferencia en la concentración en la cual se obtiene la mitad de la velocidad máxima.</li>
</ul>
</div>
</div>
<div id="modelos-no-lineales-1" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Modelos no lineales<a href="modelos-no-lineales.html#modelos-no-lineales-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>De forma general, en los modelos de regresión asumimos que:</p>
<p><span class="math display">\[
y_{i}=m(\boldsymbol x_{i},\boldsymbol \theta)+\varepsilon_{i},
\]</span>
donde <span class="math inline">\(\varepsilon_{i} \sim N(0, \sigma^2)\)</span> y <span class="math inline">\(cov(\varepsilon_{i},\varepsilon_{j}) = 0\)</span>, para todo <span class="math inline">\(i \neq j\)</span>. Particularmente, en el caso de modelos lineales, se asume que:
<span class="math display">\[
m(x_{i},\theta)=\boldsymbol x_i^{*&#39;}\boldsymbol \beta= \beta_{0}+x_{1i}^{*}\beta_{1}+x_{2i}^{*}\beta_{2}+\ldots +x_{p-1,i}^{*}\beta_{p-1},
\]</span>
donde <span class="math inline">\(x_j^{*}\)</span> representa cualquier transformación de las covariables originales, por ejemplo, <span class="math inline">\(x_j^{*}= \log x_j\)</span> o <span class="math inline">\(x_j^{*}= x_j^{2}\)</span>. Estos modelos se consideran lineales porque son combinaciones lineales de los parámetros <span class="math inline">\(\boldsymbol \beta\)</span>.</p>
<p>Modelos de la forma:
<span class="math display">\[
y_{i}=m(x_{i},\theta)+\varepsilon_{i}=\theta_{1}+\theta_{1}[1+exp(-\theta_{3}x_{i})]+\varepsilon_{i},
\]</span>
o
<span class="math display">\[
y_{i}=m(x_{i},\theta)+\varepsilon_{i}=\frac{x_{i}\theta_{i}}{\theta_{2}+x_{i}}+\varepsilon_{i},
\]</span>
son ejemplos de modelos no lineales. Es decir, no son combinación lineal de los parámetros.</p>
<div id="modelos-no-lineales-linealizables" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Modelos no-lineales linealizables<a href="modelos-no-lineales.html#modelos-no-lineales-linealizables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Dentro de los modelos no lineales se encuentran algunos que pueden ser linealizables a través de transformaciones sobre las variables. Por ejemplo, el modelo de regresión exponencial:
<span class="math display">\[
E(y)=\theta_{0}+\theta_{1}\exp(\theta_{2}+x_{i}\theta_{3}),
\]</span></p>
<p>Si <span class="math inline">\(\theta_{0}=0\)</span>, es linealizable:
<span class="math display">\[
\log y_{i}=(\log\theta_{1}+\theta_{2})+x_{i}\theta_{3}+\varepsilon_{i}^* = \beta_0+x_{i}\beta_1+\varepsilon_{i}^*
\]</span></p>
</div>
<div id="estimación-de-los-parámetros" class="section level3 hasAnchor" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Estimación de los parámetros<a href="modelos-no-lineales.html#estimación-de-los-parámetros" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Al igual que en los modelos lineales, la estimación de <span class="math inline">\(\boldsymbol \theta\)</span> se hace minimizando la suma de cuadrados de los residuos:
<span class="math display">\[
S(\boldsymbol \theta)=\sum_{i=1}^n[y_{i}-m(\boldsymbol x_{i},\boldsymbol \theta)]^2.
\]</span>
Por lo que, para encontrar el mínimo, <span class="math inline">\((1)\)</span> calculamos la derivada de <span class="math inline">\(S(\boldsymbol \theta)\)</span> con respecto a <span class="math inline">\(\boldsymbol \theta\)</span>:
<span class="math display">\[
\frac{\partial}{\partial\boldsymbol \theta}S(\boldsymbol \theta)=-2\sum_{i=1}^n[y_{i}-m(\boldsymbol x_{i},\boldsymbol \theta)]
\begin{bmatrix}\frac{\partial }{\partial\boldsymbol \theta}m(\boldsymbol x_{i},\boldsymbol \theta)\end{bmatrix}
\]</span>
<span class="math inline">\((2)\)</span> igualamos a <span class="math inline">\(0\)</span>, y <span class="math inline">\((3)\)</span> resolvemos la ecuación para <span class="math inline">\(\boldsymbol \theta\)</span>. Sin embargo, en la mayoría de los casos, <span class="math inline">\(\frac{\partial}{\partial\boldsymbol \theta}S(\boldsymbol \theta)\)</span> es una función no-lineal <span class="math inline">\(\boldsymbol \theta\)</span>. Por lo que no es posible encontrar una solución analítica y necesitamos encontrar la solución de forma <strong>iterativa</strong>.</p>
<p>Las técnicas iterativas de estimación de los parámetros están basadas en expansiones de <strong>series de Taylor</strong>. Cualquier función <span class="math inline">\(f(\theta)\)</span> puede expandirse como una serie de Taylor de la forma:
<span class="math display">\[
f(\theta)=\sum_{n=0}^\infty \frac{1}{n!}(\theta-\theta^*)^n \frac{\partial^nf(\theta^*)}{\partial\theta^n}.
\]</span>
Una aproximación de la función <span class="math inline">\(f(\theta)\)</span> en los valores alrededor del punto <span class="math inline">\(\theta^*\)</span> se puede hacer usando series de Taylor de orden dos:
<span class="math display">\[
f(\theta)\approx f(\theta^*)+(\theta-\theta^*) \frac{\partial f(\theta^*)}{\partial\theta}+\frac{1}{2}(\theta-\theta^*)^2\frac{\partial^2 f(\theta^*)}{\partial\theta^2}.
\]</span>
En caso de que <span class="math inline">\(\boldsymbol \theta\)</span> (vector de parámetros), la aproximación por series de Taylor de orden dos es:
<span class="math display">\[
f(\boldsymbol \theta)\approx f(\boldsymbol \theta^*)+(\boldsymbol \theta-\boldsymbol \theta^*)^{&#39;}u(\boldsymbol \theta^*)+\frac{1}{2}(\boldsymbol \theta-\boldsymbol \theta^*)^{&#39;}H(\boldsymbol \theta^*)(\boldsymbol \theta-\boldsymbol \theta^*),
\]</span>
donde:
<span class="math display">\[
u(\boldsymbol \theta)=\frac{\partial S(\boldsymbol \theta)}{\partial\boldsymbol \theta}=\begin{pmatrix}
\frac{\partial S(\boldsymbol \theta)}{\partial\theta_1} \\
\frac{\partial S(\boldsymbol \theta)}{\partial\theta_2} \\
\vdots \\
\frac{\partial S(\boldsymbol \theta)}{\partial\theta_p} \\
\end{pmatrix}
\qquad
u(\widehat{\boldsymbol \theta})=u(\boldsymbol \theta)|_{\boldsymbol \theta=\widehat{\boldsymbol \theta}},
\]</span>
es el vector Score, y
<span class="math display">\[
\boldsymbol H(\boldsymbol \theta)=  \frac{\partial^2 S(\boldsymbol \theta)}{\partial\boldsymbol \theta^{&#39;} \partial\boldsymbol \theta}=\begin{pmatrix} \frac{\partial^2 S(\boldsymbol \theta)}{\partial^2 \theta_{1}} &amp; \frac{\partial^2 S(\boldsymbol \theta)}{\partial \theta_{1} \partial \theta_{2} } &amp; \dots &amp; \frac{\partial^2 S(\boldsymbol \theta)}{\partial \theta_{1} \partial \theta_{p}} \\
\frac{\partial^2 S(\boldsymbol \theta)}{\partial \theta_{2} \partial \theta_{1}} &amp; \frac{\partial^2 S(\boldsymbol \theta)}{\partial^2 \theta_{2}} &amp; \dots &amp; \frac{\partial^2 S(\boldsymbol \theta)}{\partial \theta_{2} \partial \theta_{p}}\\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
\frac{\partial^2 S(\boldsymbol \theta)}{\partial \theta_{p} \partial \theta_{1}} &amp; \frac{\partial^2 S(\boldsymbol \theta)}{\partial \theta_{p} \partial \theta_{2}} &amp; \dots &amp; \frac{\partial^2 S(\boldsymbol \theta)}{\partial^2 \theta_{p}}
\end{pmatrix} \quad \quad \quad \boldsymbol H(\widehat{\boldsymbol \theta})=\boldsymbol H(\boldsymbol \theta)|_{\boldsymbol \theta=\widehat{\boldsymbol \theta}},
\]</span>
es la matriz Hessiana.</p>
<p>Algunos métodos iterativos de estimación son: Gauss-Newton (approx. series de Taylor a la función de la media) y Newton-Raphson (approx. series de Taylor a la función score). En este caso vamos a optar por el primero.</p>
<p>La idea es aproximar <span class="math inline">\(m(x_{i},\boldsymbol \theta^*)\)</span> usando series de Taylor de orden uno alrededor de <span class="math inline">\(\boldsymbol \theta^*\)</span>, esto es:</p>
<p><span class="math display" id="eq:modeloFat">\[\begin{equation}
m(x_{i},\boldsymbol \theta)\approx m(x_{i},\boldsymbol \theta^*)+(\boldsymbol \theta-\boldsymbol \theta^*)^{&#39;}u_{i}(\boldsymbol \theta^*).
\tag{4.1}
\end{equation}\]</span></p>
<p>Note que <a href="selección-de-variables.html#eq:modeloFat">(4.1)</a> tiene la forma de un modelo lineal, donde <span class="math inline">\(u_{i}(\boldsymbol \theta^*)\)</span> juega el papel de vector de covariables. La diferencia radica en que <span class="math inline">\(u_{i}(\boldsymbol \theta^*)\)</span> puede depender de los parámetros.</p>
<p>La aproximación de la suma de cuadrados de los residuos es:
<span class="math display">\[\begin{equation}
\begin{split}
S(\boldsymbol \theta)&amp;=\sum_{i=1}^n[y_{i}-m(x_{i},\boldsymbol \theta)]^2 \approx \sum_{i=1}^n[y_{i}-m(x_{i},\boldsymbol \theta^*)+(\boldsymbol \theta-\boldsymbol \theta^*)^{&#39;}u_{i}(\boldsymbol \theta^*)]^2 \\
&amp;= \sum_{i=1}^n[\widehat e_{i}^*+(\boldsymbol \theta-\boldsymbol \theta^*)^{&#39;}u_{i}(\boldsymbol \theta^*)]^2.
\end{split}
\nonumber
\end{equation}\]</span></p>
<p>Esta aproximación de <span class="math inline">\(S(\boldsymbol \theta)\)</span> es equivalente a una suma de cuadrados de un modelo lineal con <span class="math inline">\(\widehat e_{i}^*\)</span> (llamados residuos de trabajo) como variable respuesta y <span class="math inline">\(u_{i}(\boldsymbol \theta^*)\)</span> como vector de covariables. Por lo tanto, la solución es:
<span class="math display">\[
(\widehat{\boldsymbol \theta}-\boldsymbol \theta^*)=[U(\boldsymbol \theta^*)^{&#39;}U(\boldsymbol \theta^*)]^{-1}U(\boldsymbol \theta^*)^{&#39;} \widehat e^*,
\]</span>
<span class="math display" id="eq:AlgorGN">\[\begin{equation}
\hat{\boldsymbol \theta}=\boldsymbol \theta^*+[U(\boldsymbol \theta^*)^{&#39;}U(\boldsymbol \theta^*)]^{-1}U(\boldsymbol \theta^*)^{&#39;} \widehat e^*,
\tag{5.1}
\end{equation}\]</span></p>
<p>donde:<span class="math inline">\(\widehat e_{i}^*=(\widehat e_{1}^*,\ldots,\widehat e_{n}^*)^{&#39;}\)</span>, <span class="math inline">\(U(\boldsymbol \theta^*)\)</span> es una matriz con la fila <span class="math inline">\(i\)</span> igual a <span class="math inline">\(u_{i}(\boldsymbol \theta^*)\)</span>.</p>
<p>A partir de estas ecuaciones se propone el <strong>algoritmo de Gauss-Newton</strong>.</p>
<ol style="list-style-type: decimal">
<li><p>Seleccione unos valores iniciales <span class="math inline">\(\boldsymbol \theta_{0}\)</span> y calcule <span class="math inline">\(S(\boldsymbol \theta_{0})\)</span>.</p></li>
<li><p>Establezca el contador de iteraciones en <span class="math inline">\(j=0\)</span></p></li>
<li><p>Calcule <span class="math inline">\(U(\boldsymbol \theta^{(j)})\)</span> y <span class="math inline">\(\widehat e^{(j)}\)</span> y encuentre <span class="math inline">\(\boldsymbol \theta^{(j+1)}\)</span> usando <a href="modelos-no-lineales.html#eq:AlgorGN">(5.1)</a>:
<span class="math display">\[\begin{equation}
\begin{split}
&amp; \boldsymbol \theta^{(j+1)}=\boldsymbol \theta^{(j)}+[U(\boldsymbol \theta^{(j)})^{&#39;}U(\boldsymbol \theta^{(j)})]^{-1}U(\boldsymbol \theta^{(j)})^{&#39;} \widehat e^{(j)},
\end{split}
\end{equation}\]</span>
y calcule <span class="math inline">\(S(\boldsymbol \theta^{(j+1)})\)</span>.</p></li>
<li><p>Pare si <span class="math inline">\(\delta=|S(\boldsymbol \theta^{(j)})-S(\boldsymbol \theta^{(j+1)})|\)</span> es suficientemente pequeño (convergente). De otra forma, <span class="math inline">\(j=j+1\)</span> y vaya al paso 3.</p></li>
</ol>
<p>Si <span class="math inline">\(j\)</span> es muy grande (muchas iteraciones), se dice que hay divergencia.</p>
<p>La estimación de <span class="math inline">\(\sigma^2\)</span> es:</p>
<p><span class="math display">\[
\widehat{\sigma}^2=\frac{1}{n-p}\sum_{i=1}^n[y_{i}-m(\boldsymbol x_{i},\widehat{\boldsymbol \theta})]^2,
\]</span></p>
<p>donde <span class="math inline">\(p\)</span> es la dimensión de <span class="math inline">\(\boldsymbol \theta\)</span>.</p>
<p>Todos los métodos iterativos de selección requieren de la selección de valores iniciales. Para evitar problemas de divergencia, es preferible escoger valores que estén cercanos a los parámetros. Esto se puede lograr basándose en conocimiento previo del problema, significado físico de los coeficientes, evaluación gráfica o linealización de los datos. Otro aspecto que se debe tener en cuenta es que este tipo de algoritmos pueden caer en un máximo local. Por lo que es recomendable ejecutar el algoritmo para diferentes valores iniciales.</p>
<p>En el caso del peso de los pavos, se pueden utilizar los siguientes valores iniciales:</p>
<ul>
<li><p><span class="math inline">\(\theta_{1}^0=620\)</span> (promedio del peso ganado sin suplemento).</p></li>
<li><p><span class="math inline">\(\theta_{2}^0+\theta_{1}^0=800\)</span> (valor cercano al máximo peso obtenido). Por lo tanto <span class="math inline">\(\theta_{2}^0=180\)</span></p></li>
<li><p><span class="math inline">\(\theta_{3}^0\)</span> se puede obtener resolviendo la siguiente ecuación <span class="math inline">\(E(y) = \theta_1^{0}+\theta_2^{0}[1-exp(-\theta_{3} A)]\)</span> para un posible punto. Por ejemplo, si <span class="math inline">\(A=0.16\)</span>, un valor posible para <span class="math inline">\(E(y)\)</span> es 750. Por lo que:
<span class="math display">\[
750=620+180[1-\exp(-\theta_{3}^00.16)].
\]</span>
Resolviendo la ecuación <span class="math inline">\(\theta_{3}^0\approx8\)</span>.</p></li>
</ul>
<p>En R, la estimación del modelo lineal se hace usando la función ´nls()´. Para el caso de crecimiento de los pavos:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="modelos-no-lineales.html#cb97-1" tabindex="-1"></a>mod.turk <span class="ot">=</span> <span class="fu">nls</span>(Gain <span class="sc">~</span> th1 <span class="sc">+</span> th2<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">exp</span>(<span class="sc">-</span>th3<span class="sc">*</span>A)),<span class="at">data =</span> turk0,</span>
<span id="cb97-2"><a href="modelos-no-lineales.html#cb97-2" tabindex="-1"></a>          <span class="at">start =</span> <span class="fu">list</span>(<span class="at">th1=</span><span class="dv">620</span>,<span class="at">th2=</span><span class="dv">180</span>,<span class="at">th3=</span><span class="dv">8</span>),<span class="at">trace=</span>F)</span>
<span id="cb97-3"><a href="modelos-no-lineales.html#cb97-3" tabindex="-1"></a>mod.turk</span></code></pre></div>
<pre><code>## Nonlinear regression model
##   model: Gain ~ th1 + th2 * (1 - exp(-th3 * A))
##    data: turk0
##     th1     th2     th3 
## 622.958 178.252   7.122 
##  residual sum-of-squares: 12367
## 
## Number of iterations to convergence: 4 
## Achieved convergence tolerance: 6.736e-06</code></pre>
<p>Por lo que la estimación de la media del peso ganado por corral es:
<span class="math display">\[
E(\mbox{Gain}|A)=622.958 + 178.252 [1 - \exp(-7.122A)]    
\]</span>
La figura <a href="modelos-no-lineales.html#fig:plotpavoscrec">5.4</a> muestra el ajuste de forma gráfica.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="modelos-no-lineales.html#cb99-1" tabindex="-1"></a><span class="fu">plot</span>(Gain<span class="sc">~</span>A,<span class="at">data=</span>turk0,<span class="at">xlab=</span><span class="st">&#39;cantidad de metionina (% dieta)&#39;</span>,<span class="at">ylab=</span><span class="st">&#39;Peso ganado (gramos)&#39;</span>)</span>
<span id="cb99-2"><a href="modelos-no-lineales.html#cb99-2" tabindex="-1"></a>th.turk <span class="ot">=</span> <span class="fu">coef</span>(mod.turk)</span>
<span id="cb99-3"><a href="modelos-no-lineales.html#cb99-3" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="fl">0.5</span>,<span class="at">length.out=</span><span class="dv">100</span>)</span>
<span id="cb99-4"><a href="modelos-no-lineales.html#cb99-4" tabindex="-1"></a><span class="fu">lines</span>(x, th.turk[<span class="dv">1</span>]<span class="sc">+</span>th.turk[<span class="dv">2</span>]<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">exp</span>(<span class="sc">-</span>th.turk[<span class="dv">3</span>]<span class="sc">*</span>x)),<span class="at">col=</span><span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plotpavoscrec"></span>
<img src="MLG2_files/figure-html/plotpavoscrec-1.png" alt="Datos crecimiento de pavos. Ajuste del modelo para el peso medio ganado por corral en función de la cantidad de suplemento de metionina." width="576" />
<p class="caption">
Figure 5.4: Datos crecimiento de pavos. Ajuste del modelo para el peso medio ganado por corral en función de la cantidad de suplemento de metionina.
</p>
</div>
</div>
<div id="inferencia-sobre-los-parámetros" class="section level3 hasAnchor" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> Inferencia sobre los parámetros<a href="modelos-no-lineales.html#inferencia-sobre-los-parámetros" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Las propiedades del <span class="math inline">\(\widehat{\boldsymbol \theta}\)</span> se basan en teoría asintótica, es decir que son válidas si se tiene muestras grandes. Si <span class="math inline">\(\varepsilon \sim N(\boldsymbol 0,\sigma^2 \boldsymbol I)\)</span>, tenemos que asintóticamente <span class="math inline">\((n \to \infty)\)</span>:</p>
<p><span class="math display">\[
\widehat{\boldsymbol \theta}\sim N\left(\boldsymbol \theta,\sigma^2\left[U(\boldsymbol \theta^*)U(\boldsymbol \theta^*)&#39;\right]^{-1}\right).
\]</span>
Esto quiere decir que, <span class="math inline">\(\widehat{\boldsymbol \theta}\)</span> es un estimador asintoticamente insesgado de <span class="math inline">\(\boldsymbol \theta\)</span> y se distribuye de forma normal. Además, se puede probar que es un estimador eficiente (mínima varianza).</p>
<p>A partir de estos resultados se pueden hacer inferencias sobre los coeficientes <span class="math inline">\(\boldsymbol \theta\)</span>. Por ejemplo, pruebas de hipótesis sobre algún coeficiente del modelo:
<span class="math display">\[
\qquad H_{0}:\theta_{j}=\theta_{0}, \qquad H_{1}:\theta_{j}\ne\theta_{0},
\]</span>
se puede hacer a través del siguiente estadístico de prueba:
<span class="math display">\[
t_{0}:\frac{\widehat{\theta_{j}}-\theta_{0}}{\sqrt{V(\widehat{\theta_{j}})}}, \quad \text{donde} \quad t_{0} \sim t_{n-p}.
\]</span>
También, pruebas de hipótesis para subconjuntos de parámetros:
<span class="math display">\[
H_{0}:\boldsymbol \theta_{2}=\boldsymbol 0\qquad H_{1}:\boldsymbol \theta_{2}\ne\boldsymbol 0,
\]</span>
donde <span class="math inline">\(\boldsymbol \theta=(\boldsymbol \theta_{1}^{&#39;},\boldsymbol \theta_{2}^{&#39;})^{&#39;}\)</span>. En este caso, el estadístico de prueba es:
<span class="math display">\[
F_{0}=\frac{[SS_{res}(\boldsymbol \theta)-SS_{res}(\boldsymbol \theta_{1})]/r}{MS_{res}(\boldsymbol \theta)}\sim F_{r,n-p}.
\]</span>
De igual forma, intervalos de confianza del del <span class="math inline">\((1-\alpha)\)</span>% para <span class="math inline">\(\theta_{j}\)</span>:</p>
<p><span class="math display">\[
\hat{\theta_{j}}\pm t_{1-\alpha/2,n-p}\sqrt{V(\hat{\theta_{j}})} ,
\]</span>
o intervalos de confianza del del <span class="math inline">\((1-\alpha)\)</span>% para <span class="math inline">\(E(Y|x_{0})\)</span>.Con la función <code>confint</code> de R se pueden obtener los IC de los coeficientes a través de los perfiles de verosimilitud.</p>
<p>Hay que hacer énfasis que estas son propiedades para muestras grandes, para muestras pequeñas, estas propiedades pueden ser inadecuadas y se puede recurrir a otras alternativas, como el <strong>bootstrap</strong>.</p>
<p>Para el modelo de crecimiento de los pavos, tenemos que:</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="modelos-no-lineales.html#cb100-1" tabindex="-1"></a><span class="fu">summary</span>(mod.turk)</span></code></pre></div>
<pre><code>## 
## Formula: Gain ~ th1 + th2 * (1 - exp(-th3 * A))
## 
## Parameters:
##     Estimate Std. Error t value Pr(&gt;|t|)    
## th1  622.958      5.901  105.57  &lt; 2e-16 ***
## th2  178.252     11.636   15.32 2.74e-16 ***
## th3    7.122      1.205    5.91 1.41e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 19.66 on 32 degrees of freedom
## 
## Number of iterations to convergence: 4 
## Achieved convergence tolerance: 6.736e-06</code></pre>
<p>A partir de este ajuste se puede concluir que el peso medio obtenido sin suplemento es de <span class="math inline">\(622\)</span>. Mientras que la ganancia máxima que se obtiene con el suplemento es de <span class="math inline">\(178\)</span> (significativemente mayor de cero). Los intervalos de confianza para <span class="math inline">\(\boldsymbol \theta\)</span> se obtienen de la siguiente forma:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="modelos-no-lineales.html#cb102-1" tabindex="-1"></a><span class="fu">confint</span>(mod.turk)</span></code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##           2.5%      97.5%
## th1 610.970918 634.855196
## th2 156.322676 204.476710
## th3   4.966356   9.777723</code></pre>
<p>Aquí podemos ver que, por ejemplo, la ganancia máxima que se puede obtener con el suplemento está entre <span class="math inline">\(156\)</span> y <span class="math inline">\(204\)</span> gramos con un nivel de confianza del 95%.</p>
<p>Para calcular los intervalos de confianza para la media podemos utilizar la función <code>predFit</code> de la librería <code>investr</code>. La Figura <a href="modelos-no-lineales.html#fig:Confintpavos2">5.5</a> muestra el intervalo del 95% del peso ganado medio en función del % de metionina en la dieta.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="modelos-no-lineales.html#cb105-1" tabindex="-1"></a><span class="fu">library</span>(investr)</span></code></pre></div>
<pre><code>## Warning: package &#39;investr&#39; was built under R version 4.2.3</code></pre>
<pre><code>## 
## Attaching package: &#39;investr&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:VGAM&#39;:
## 
##     calibrate</code></pre>
<pre><code>## The following object is masked from &#39;package:faraway&#39;:
## 
##     beetle</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="modelos-no-lineales.html#cb110-1" tabindex="-1"></a>predx <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">A=</span><span class="fu">seq</span>(<span class="at">from=</span><span class="dv">0</span>,<span class="at">to=</span><span class="fl">0.5</span>,<span class="at">length.out=</span><span class="dv">100</span>))</span>
<span id="cb110-2"><a href="modelos-no-lineales.html#cb110-2" tabindex="-1"></a></span>
<span id="cb110-3"><a href="modelos-no-lineales.html#cb110-3" tabindex="-1"></a>predGain <span class="ot">=</span> <span class="fu">predFit</span>(mod.turk,predx,<span class="at">interval=</span><span class="st">&#39;confidence&#39;</span>)</span>
<span id="cb110-4"><a href="modelos-no-lineales.html#cb110-4" tabindex="-1"></a></span>
<span id="cb110-5"><a href="modelos-no-lineales.html#cb110-5" tabindex="-1"></a><span class="fu">plot</span>(Gain<span class="sc">~</span>A,<span class="at">data=</span>turk0,<span class="at">xlab=</span><span class="st">&#39;cantidad de metionina (% dieta)&#39;</span>,<span class="at">ylab=</span><span class="st">&#39;Peso ganado (gramos)&#39;</span>)</span>
<span id="cb110-6"><a href="modelos-no-lineales.html#cb110-6" tabindex="-1"></a>th <span class="ot">=</span> <span class="fu">coef</span>(mod.turk)</span>
<span id="cb110-7"><a href="modelos-no-lineales.html#cb110-7" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="fl">0.5</span>,<span class="at">length.out=</span><span class="dv">100</span>)</span>
<span id="cb110-8"><a href="modelos-no-lineales.html#cb110-8" tabindex="-1"></a><span class="fu">lines</span>(x, th.turk[<span class="dv">1</span>]<span class="sc">+</span>th.turk[<span class="dv">2</span>]<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">exp</span>(<span class="sc">-</span>th.turk[<span class="dv">3</span>]<span class="sc">*</span>x)),<span class="at">col=</span><span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb110-9"><a href="modelos-no-lineales.html#cb110-9" tabindex="-1"></a><span class="fu">lines</span>(predx<span class="sc">$</span>A,predGain[,<span class="dv">2</span>],<span class="at">col=</span><span class="dv">2</span>,<span class="at">lty=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb110-10"><a href="modelos-no-lineales.html#cb110-10" tabindex="-1"></a><span class="fu">lines</span>(predx<span class="sc">$</span>A,predGain[,<span class="dv">3</span>],<span class="at">col=</span><span class="dv">2</span>,<span class="at">lty=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Confintpavos2"></span>
<img src="MLG2_files/figure-html/Confintpavos2-1.png" alt="Datos pavos. Intervalo del 95% de confianza para la media del peso ganado en función de la dieta." width="960" />
<p class="caption">
Figure 5.5: Datos pavos. Intervalo del 95% de confianza para la media del peso ganado en función de la dieta.
</p>
</div>
<p>Es posible considerar otros modelos de crecimiento para este conjunto de datos. Algunos de estos son:</p>
<ul>
<li>Modelo logístico:</li>
</ul>
<p><span class="math display">\[
y_{i}=\frac{\theta_{1}}{1+\theta_{2}\exp(-\theta_{3}x_{i})}+\varepsilon_{i},
\]</span>
- Modelo Weibull:</p>
<p><span class="math display">\[
y_{i}=\theta_{1}+\theta_{2}[1-\exp(-\theta_{3}x_{i}^{\theta_{4}})]+\varepsilon_{i}.
\]</span>
Para compararlos, podemos ajustarlos y verificar cuál de los tres proporciona mejor ajuste usando criterios de información (AIC o BIC). En la Figura @ref{fig:tresmodelospavos}, y a través del BIC, podemos ver que los tres modelos proporcionan casi el mismo ajuste. Así que, cualquiera puede ser usado para hacer inferencias y sacar conclusiones.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="modelos-no-lineales.html#cb111-1" tabindex="-1"></a><span class="fu">plot</span>(Gain<span class="sc">~</span>A,<span class="at">data=</span>turk0,<span class="at">xlab=</span><span class="st">&#39;cantidad de metionina (% dieta)&#39;</span>,<span class="at">ylab=</span><span class="st">&#39;Peso ganado (gramos)&#39;</span>)</span>
<span id="cb111-2"><a href="modelos-no-lineales.html#cb111-2" tabindex="-1"></a></span>
<span id="cb111-3"><a href="modelos-no-lineales.html#cb111-3" tabindex="-1"></a>mod2 <span class="ot">=</span> <span class="fu">nls</span>(Gain <span class="sc">~</span> th1<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span>th2<span class="sc">*</span><span class="fu">exp</span>(<span class="sc">-</span>th3<span class="sc">*</span>A)),<span class="at">data =</span> turk0,</span>
<span id="cb111-4"><a href="modelos-no-lineales.html#cb111-4" tabindex="-1"></a>           <span class="at">start =</span> <span class="fu">list</span>(<span class="at">th1=</span><span class="dv">620</span>,<span class="at">th2=</span><span class="fl">0.25</span>,<span class="at">th3=</span><span class="dv">8</span>) )</span>
<span id="cb111-5"><a href="modelos-no-lineales.html#cb111-5" tabindex="-1"></a></span>
<span id="cb111-6"><a href="modelos-no-lineales.html#cb111-6" tabindex="-1"></a>mod3 <span class="ot">=</span> <span class="fu">nls</span>(Gain <span class="sc">~</span> th1 <span class="sc">+</span> th2<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">exp</span>(<span class="sc">-</span>th3<span class="sc">*</span>A<span class="sc">^</span>th4)),<span class="at">data =</span> turk0,</span>
<span id="cb111-7"><a href="modelos-no-lineales.html#cb111-7" tabindex="-1"></a>           <span class="at">start =</span> <span class="fu">list</span>(<span class="at">th1=</span><span class="dv">800</span>,<span class="at">th2=</span><span class="dv">180</span>,<span class="at">th3=</span><span class="dv">8</span>,<span class="at">th4=</span><span class="dv">1</span>) )</span>
<span id="cb111-8"><a href="modelos-no-lineales.html#cb111-8" tabindex="-1"></a>           </span>
<span id="cb111-9"><a href="modelos-no-lineales.html#cb111-9" tabindex="-1"></a>th2 <span class="ot">=</span> <span class="fu">coef</span>(mod2)         </span>
<span id="cb111-10"><a href="modelos-no-lineales.html#cb111-10" tabindex="-1"></a>th3 <span class="ot">=</span> <span class="fu">coef</span>(mod3)</span>
<span id="cb111-11"><a href="modelos-no-lineales.html#cb111-11" tabindex="-1"></a><span class="fu">lines</span>(x, th[<span class="dv">1</span>]<span class="sc">+</span>th[<span class="dv">2</span>]<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">exp</span>(<span class="sc">-</span>th[<span class="dv">3</span>]<span class="sc">*</span>x)),<span class="at">col=</span><span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb111-12"><a href="modelos-no-lineales.html#cb111-12" tabindex="-1"></a><span class="fu">lines</span>(x, th2[<span class="dv">1</span>]<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span>th2[<span class="dv">2</span>]<span class="sc">*</span><span class="fu">exp</span>(<span class="sc">-</span>th2[<span class="dv">3</span>]<span class="sc">*</span>x)),<span class="at">col=</span><span class="dv">3</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb111-13"><a href="modelos-no-lineales.html#cb111-13" tabindex="-1"></a><span class="fu">lines</span>(x, th3[<span class="dv">1</span>]<span class="sc">+</span>th3[<span class="dv">2</span>]<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">exp</span>(<span class="sc">-</span>th3[<span class="dv">3</span>]<span class="sc">*</span>x<span class="sc">^</span>th3[<span class="dv">4</span>])),<span class="at">col=</span><span class="dv">4</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:tresmodelospavos"></span>
<img src="MLG2_files/figure-html/tresmodelospavos-1.png" alt="Datos crecimiento de pavos. Ajuste del modelo de crecimiento propuesto (rojo), modelo logístico (verde) y Modelo Weibull (azul)." width="672" />
<p class="caption">
Figure 5.6: Datos crecimiento de pavos. Ajuste del modelo de crecimiento propuesto (rojo), modelo logístico (verde) y Modelo Weibull (azul).
</p>
</div>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="modelos-no-lineales.html#cb112-1" tabindex="-1"></a><span class="fu">BIC</span>(mod.turk)</span></code></pre></div>
<pre><code>## [1] 318.9086</code></pre>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="modelos-no-lineales.html#cb114-1" tabindex="-1"></a><span class="fu">BIC</span>(mod2)</span></code></pre></div>
<pre><code>## [1] 318.6193</code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="modelos-no-lineales.html#cb116-1" tabindex="-1"></a><span class="fu">BIC</span>(mod3)</span></code></pre></div>
<pre><code>## [1] 322.3054</code></pre>
<div id="puromicina-estimación" class="section level4 hasAnchor" number="5.2.3.1">
<h4><span class="header-section-number">5.2.3.1</span> Puromicina-Estimación<a href="modelos-no-lineales.html#puromicina-estimación" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Los valores iniciales del modelo Michaelis-Menten se puede hacer por linealización. Tenemos que:
<span class="math display">\[
m(\boldsymbol x,\boldsymbol \theta) = \frac{\theta_1 x}{x + \theta_2},
\]</span>
es linealizable aplicando la inversa a ambos lados de la ecuación:
<span class="math display">\[
\frac{1}{m(\boldsymbol x,\boldsymbol \theta)} = \frac{x + \theta_2}{\theta_1 x} = \frac{1}{\theta_1} + \frac{1}{x}\frac{\theta_2}{\theta_1}.
\]</span>
En la Figura <a href="modelos-no-lineales.html#fig:linealpuromicina">5.7</a> podemos ver que aplicando inversas a ambas variables se obtiene una relación aproximadamente lineal.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:linealpuromicina"></span>
<img src="MLG2_files/figure-html/linealpuromicina-1.png" alt="Datos puromicina. Diagrama de dispersión. Datos linealizados(derecha)." width="672" />
<p class="caption">
Figure 5.7: Datos puromicina. Diagrama de dispersión. Datos linealizados(derecha).
</p>
</div>
<p>A través del ajuste por MCO para:</p>
<p><span class="math display">\[
1/y_{i}=\beta_{0}+1/\mbox{conc}_{i}\beta_{1}+\varepsilon_{i},
\]</span>
se puede obtener valores iniciales. Luego de ajustar el modelo se obtiene que:</p>
<p><span class="math display">\[
\theta_{1}^{(0)}=\frac{1}{\hat{\beta}_{0}}=167.408 \qquad \theta_{2}^{(0)}=\frac{\hat{\beta}_{1}}{\hat{\beta}_{0}}=0.039
\]</span>
Inicialmente, se podríamos asumir que <span class="math inline">\(\beta_{3}^{(0)}=\beta_{4}^{(0)}=0\)</span> (es decir, no hay diferencias entre las células tratadas y no tratadas). Usando la función ´nls()´ de R obtenemos los siguientes resultados:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="modelos-no-lineales.html#cb118-1" tabindex="-1"></a>Puromycin<span class="sc">$</span>state2 <span class="ot">=</span> <span class="fu">as.double</span>(Puromycin<span class="sc">$</span>state <span class="sc">==</span> <span class="st">&#39;treated&#39;</span>)</span>
<span id="cb118-2"><a href="modelos-no-lineales.html#cb118-2" tabindex="-1"></a>mod.puromicyn <span class="ot">=</span> <span class="fu">nls</span>(rate <span class="sc">~</span> (th1<span class="sc">*</span>conc <span class="sc">+</span> th3<span class="sc">*</span>conc<span class="sc">*</span>state2)<span class="sc">/</span>(th2<span class="sc">+</span>th4<span class="sc">*</span>state2<span class="sc">+</span>conc),<span class="at">data =</span> Puromycin,</span>
<span id="cb118-3"><a href="modelos-no-lineales.html#cb118-3" tabindex="-1"></a>          <span class="at">start =</span> <span class="fu">list</span>(<span class="at">th1=</span><span class="dv">168</span>,<span class="at">th2=</span><span class="fl">0.4</span>,<span class="at">th3=</span><span class="dv">0</span>,<span class="at">th4=</span><span class="dv">0</span>),<span class="at">trace=</span>F )</span>
<span id="cb118-4"><a href="modelos-no-lineales.html#cb118-4" tabindex="-1"></a><span class="fu">summary</span>(mod.puromicyn )</span></code></pre></div>
<pre><code>## 
## Formula: rate ~ (th1 * conc + th3 * conc * state2)/(th2 + th4 * state2 + 
##     conc)
## 
## Parameters:
##      Estimate Std. Error t value Pr(&gt;|t|)    
## th1 1.603e+02  6.896e+00  23.242 2.04e-15 ***
## th2 4.771e-02  8.281e-03   5.761 1.50e-05 ***
## th3 5.240e+01  9.551e+00   5.487 2.71e-05 ***
## th4 1.641e-02  1.143e-02   1.436    0.167    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.4 on 19 degrees of freedom
## 
## Number of iterations to convergence: 7 
## Achieved convergence tolerance: 3.018e-06</code></pre>
<p>Con estos resultados podemos concluir que la tasa de crecimiento máxima es diferente si la enzima es tratada o no (<span class="math inline">\(\theta_3\)</span> es significativamente diferente de cero). Sin embargo, el punto en que se alcanza la mitad del máximo es el mismos (<span class="math inline">\(\theta_4\)</span> no es significativamente diferente de cero). El ajuste se puede observar de forma gráfica en la Figura <a href="modelos-no-lineales.html#fig:puromicinaplotl">5.8</a>. Las líneas horizontales muestran la diferencia entre las asíntotas entre las céludas tratadas y las no tratadas. Mientras que, las líneas verticales la concentración donde se obtiene la mitad de la velocidad de reacción máxima.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:puromicinaplotl"></span>
<img src="MLG2_files/figure-html/puromicinaplotl-1.png" alt="Datos puromicina. Enzimas tratadas(negro), enzimas no tratadas(rojo). " width="672" />
<p class="caption">
Figure 5.8: Datos puromicina. Enzimas tratadas(negro), enzimas no tratadas(rojo).
</p>
</div>
</div>
</div>
</div>
<div id="método-de-bootstrap" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Método de Bootstrap<a href="modelos-no-lineales.html#método-de-bootstrap" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Los métodos de inferencia que se muestran anteriormente se basan en la distribución asintótica de los estimadores. Por lo que pueden ser inexactas y/o engañosas si tenemos muestras pequeñas. En esos casos, una alternativa preferible es usar ténicas de remuestreo (<strong>bootstrap</strong>).</p>
<p>El bootstrap es una técnica que se puede usar para calcular intervalos de confianza and pruebas de hipótesis cuando el cumplimiento de los supuestos asumidos en el modelo están en duda. Por ejemplo, si se quiere calcular un intervalo de confianza para la mediana (o cualquier otro parámetro) de <span class="math inline">\(Y\)</span>. Para esto tomamos una muestra
independiente <span class="math inline">\(\boldsymbol y=(y_{1},...,y_{n})\)</span>.</p>
<p>Pasos del boostrap:</p>
<ol style="list-style-type: decimal">
<li>Obtener una muestra aleatoria con remuestreo de <span class="math inline">\(\boldsymbol y=(y_{1}^{*},...,y_{n}^{*})\)</span>.</li>
<li>Calcular la mediana usando la muestra el paso 1 <span class="math inline">\((Me_{1})\)</span>.</li>
<li>Repita los pasos 1 y 2 un número grande de veces <span class="math inline">\((B)\)</span>.</li>
<li>un intervalo de confianza del 95% basado en percentiles muestrales 2.5% y 97.5 %.</li>
</ol>
<div id="bootstrap-en-regresión" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Bootstrap en regresión<a href="modelos-no-lineales.html#bootstrap-en-regresión" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para un modelo de regresión, el remuestreo se hace sobre los observaciones, considerando la respuesta y las covariables, <span class="math inline">\((y_i,\boldsymbol x_i)\)</span>, o sobre los residuos del ajuste por MCO. El segundo método es llamado residual resampling y se realiza de las siguiente forma:</p>
<ol style="list-style-type: decimal">
<li><p>Con la muestra dada: <span class="math inline">\((x_{i},y_{i}),i=1,...,n\)</span> ajustar el modelo y obtener los residuos: <span class="math inline">\(e_{i}=y_{i}-x_{i}^{&#39;}\hat{\beta}.\)</span></p></li>
<li><p>Obtener una muestra aleatoria con reemplazo de los residuos <span class="math inline">\(e^*=(e_{1}^*,...,e_{n}^*)\)</span>.</p></li>
</ol>
<p>3.Crear una variable respuesta bootstrap con <span class="math inline">\(y_{i}^*=x_{i}^{&#39;}\hat{\beta}+e_{1}^*\)</span> y estimar <span class="math inline">\(\hat{\beta}^*\)</span>.</p>
<ol start="4" style="list-style-type: decimal">
<li>Repetir los pasos 1-3 un número grande de veces <span class="math inline">\((B)\)</span> y obtener
el intervalo de confianza para <span class="math inline">\(\beta_{j}\)</span> usando los percentiles*.</li>
</ol>
<p><span class="math inline">\(*\)</span>Hay muchas modificaciones y extensiones para calcular los intervalos de confianza.</p>
<p>Para los datos de la Puromicina, el bootstrap en R se puede implementar utilizando la función <code>Boot</code> de la librería <code>car</code>:</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="modelos-no-lineales.html#cb120-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">310</span>)</span>
<span id="cb120-2"><a href="modelos-no-lineales.html#cb120-2" tabindex="-1"></a>mod.boot <span class="ot">=</span> <span class="fu">Boot</span>(mod.puromicyn,<span class="at">method=</span><span class="st">&#39;residual&#39;</span>,<span class="at">R=</span><span class="dv">1000</span>)</span></code></pre></div>
<pre><code>## 
##  Number of bootstraps was 999 out of 1000 attempted</code></pre>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="modelos-no-lineales.html#cb122-1" tabindex="-1"></a>mod.boot</span></code></pre></div>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot::boot(data = data.frame(update(object, model = TRUE)$model), 
##     statistic = boot.f, R = R, .fn = f, parallel = p_type, ncpus = ncores, 
##     cl = cl2)
## 
## 
## Bootstrap Statistics :
##         original        bias    std. error
## t1* 160.27996768  8.879761e-01 6.341551999
## t2*   0.04770806 -2.301129e-05 0.007476639
## t3*  52.40375392  9.728504e-02 8.901228953
## t4*   0.01641319 -1.930537e-05 0.010523158</code></pre>
<p>En el objeto <code>mod.boot</code> se pueden observar todas las estimaciones calculadas en los <span class="math inline">\(1000\)</span> remuestreos. Por ejemplo, la relaciones entre las estimaciones se pueden observar a través de un diagrama de dispersión (Figura <a href="modelos-no-lineales.html#fig:bootgraf">5.9</a>). Aquí vemos una correlaciones altas en algunas de las estimaciones.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="modelos-no-lineales.html#cb124-1" tabindex="-1"></a><span class="fu">pairs</span>(mod.boot<span class="sc">$</span>t,<span class="at">labels=</span><span class="fu">c</span>(<span class="fu">expression</span>(<span class="fu">hat</span>(theta)[<span class="dv">1</span>]),<span class="fu">expression</span>(<span class="fu">hat</span>(theta)[<span class="dv">2</span>]),<span class="fu">expression</span>(<span class="fu">hat</span>(theta)[<span class="dv">3</span>]),</span>
<span id="cb124-2"><a href="modelos-no-lineales.html#cb124-2" tabindex="-1"></a>                          <span class="fu">expression</span>(<span class="fu">hat</span>(theta)[<span class="dv">4</span>])))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:bootgraf"></span>
<img src="MLG2_files/figure-html/bootgraf-1.png" alt="Datos puromicina. Diagrama de dispersión para las estimaciones de los coeficientes del modelo por bootstrap." width="672" />
<p class="caption">
Figure 5.9: Datos puromicina. Diagrama de dispersión para las estimaciones de los coeficientes del modelo por bootstrap.
</p>
</div>
<p>Igualmente, la distribución muestral de los estimadores de los coeficientes se pueden obtener a partir de histogramas (ver Figura <a href="modelos-no-lineales.html#fig:bootgrafconf">5.10</a>). Estas parecen aproximarse a distribuciones normales, sin embargo, hay leves asimetrías en <span class="math inline">\(\hattheta_1\)</span> y <span class="math inline">\(\hattheta_2\)</span>.</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="modelos-no-lineales.html#cb125-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">4</span>))</span>
<span id="cb125-2"><a href="modelos-no-lineales.html#cb125-2" tabindex="-1"></a><span class="fu">hist</span>(mod.boot<span class="sc">$</span>t[,<span class="dv">1</span>],<span class="at">breaks =</span> <span class="dv">20</span>,<span class="at">xlab=</span><span class="fu">expression</span>(<span class="fu">hat</span>(theta)[<span class="dv">1</span>]),<span class="at">main =</span> <span class="st">&#39;&#39;</span>)</span>
<span id="cb125-3"><a href="modelos-no-lineales.html#cb125-3" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">coef</span>(mod.puromicyn)[<span class="dv">1</span>],<span class="at">lty=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb125-4"><a href="modelos-no-lineales.html#cb125-4" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(mod.boot<span class="sc">$</span>t[,<span class="dv">1</span>]),<span class="at">lty=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb125-5"><a href="modelos-no-lineales.html#cb125-5" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">quantile</span>(mod.boot<span class="sc">$</span>t[,<span class="dv">1</span>],<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>),<span class="at">na.rm =</span> T),<span class="at">lty=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb125-6"><a href="modelos-no-lineales.html#cb125-6" tabindex="-1"></a></span>
<span id="cb125-7"><a href="modelos-no-lineales.html#cb125-7" tabindex="-1"></a><span class="fu">hist</span>(mod.boot<span class="sc">$</span>t[,<span class="dv">2</span>],<span class="at">breaks =</span> <span class="dv">20</span>,<span class="at">xlab=</span><span class="fu">expression</span>(<span class="fu">hat</span>(theta)[<span class="dv">2</span>]),<span class="at">main =</span> <span class="st">&#39;&#39;</span>)</span>
<span id="cb125-8"><a href="modelos-no-lineales.html#cb125-8" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">coef</span>(mod.puromicyn)[<span class="dv">2</span>],<span class="at">lty=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb125-9"><a href="modelos-no-lineales.html#cb125-9" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(mod.boot<span class="sc">$</span>t[,<span class="dv">2</span>]),<span class="at">lty=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb125-10"><a href="modelos-no-lineales.html#cb125-10" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">quantile</span>(mod.boot<span class="sc">$</span>t[,<span class="dv">2</span>],<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>),<span class="at">na.rm =</span> T),<span class="at">lty=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb125-11"><a href="modelos-no-lineales.html#cb125-11" tabindex="-1"></a></span>
<span id="cb125-12"><a href="modelos-no-lineales.html#cb125-12" tabindex="-1"></a><span class="fu">hist</span>(mod.boot<span class="sc">$</span>t[,<span class="dv">3</span>],<span class="at">breaks =</span> <span class="dv">20</span>,<span class="at">xlab=</span><span class="fu">expression</span>(theta[<span class="dv">3</span>]),<span class="at">main =</span> <span class="st">&#39;&#39;</span>)</span>
<span id="cb125-13"><a href="modelos-no-lineales.html#cb125-13" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">coef</span>(mod.puromicyn)[<span class="dv">3</span>],<span class="at">lty=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb125-14"><a href="modelos-no-lineales.html#cb125-14" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(mod.boot<span class="sc">$</span>t[,<span class="dv">3</span>]),<span class="at">lty=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb125-15"><a href="modelos-no-lineales.html#cb125-15" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">quantile</span>(mod.boot<span class="sc">$</span>t[,<span class="dv">3</span>],<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>),<span class="at">na.rm =</span> T),<span class="at">lty=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb125-16"><a href="modelos-no-lineales.html#cb125-16" tabindex="-1"></a></span>
<span id="cb125-17"><a href="modelos-no-lineales.html#cb125-17" tabindex="-1"></a><span class="fu">hist</span>(mod.boot<span class="sc">$</span>t[,<span class="dv">4</span>],<span class="at">breaks =</span> <span class="dv">20</span>,<span class="at">xlab=</span><span class="fu">expression</span>(theta[<span class="dv">4</span>]),<span class="at">main =</span> <span class="st">&#39;&#39;</span>)</span>
<span id="cb125-18"><a href="modelos-no-lineales.html#cb125-18" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">coef</span>(mod.puromicyn)[<span class="dv">4</span>],<span class="at">lty=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb125-19"><a href="modelos-no-lineales.html#cb125-19" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(mod.boot<span class="sc">$</span>t[,<span class="dv">4</span>]),<span class="at">lty=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb125-20"><a href="modelos-no-lineales.html#cb125-20" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">quantile</span>(mod.boot<span class="sc">$</span>t[,<span class="dv">4</span>],<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>),<span class="at">na.rm =</span> T),<span class="at">lty=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:bootgrafconf"></span>
<img src="MLG2_files/figure-html/bootgrafconf-1.png" alt="Datos puromicina. Histograma de las estimaciones de los coeficientes del modelo por bootstrap. Linea negra: estimación por mínimos cuadrados.Lineas rojas: percentil 2.5, media y percentil 97.5." width="672" />
<p class="caption">
Figure 5.10: Datos puromicina. Histograma de las estimaciones de los coeficientes del modelo por bootstrap. Linea negra: estimación por mínimos cuadrados.Lineas rojas: percentil 2.5, media y percentil 97.5.
</p>
</div>
<p>Finalmente, los intervalos del 95% de confianza usando bootstrap se pueden obtener a partir de los percentiles 2.5% y 97.5% de las distribuciones remuestreadas:</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="modelos-no-lineales.html#cb126-1" tabindex="-1"></a><span class="fu">quantile</span>(mod.boot<span class="sc">$</span>t[,<span class="dv">1</span>],<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>),<span class="at">na.rm =</span> T)</span></code></pre></div>
<pre><code>##     2.5%    97.5% 
## 150.2763 175.1425</code></pre>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="modelos-no-lineales.html#cb128-1" tabindex="-1"></a><span class="fu">quantile</span>(mod.boot<span class="sc">$</span>t[,<span class="dv">2</span>],<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>),<span class="at">na.rm =</span> T)</span></code></pre></div>
<pre><code>##       2.5%      97.5% 
## 0.03538444 0.06329289</code></pre>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="modelos-no-lineales.html#cb130-1" tabindex="-1"></a><span class="fu">quantile</span>(mod.boot<span class="sc">$</span>t[,<span class="dv">3</span>],<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>),<span class="at">na.rm =</span> T)</span></code></pre></div>
<pre><code>##    2.5%   97.5% 
## 34.8151 70.2094</code></pre>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="modelos-no-lineales.html#cb132-1" tabindex="-1"></a><span class="fu">quantile</span>(mod.boot<span class="sc">$</span>t[,<span class="dv">4</span>],<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>),<span class="at">na.rm =</span> T)</span></code></pre></div>
<pre><code>##        2.5%       97.5% 
## -0.00663091  0.03540431</code></pre>
<p>En la Figura <a href="modelos-no-lineales.html#fig:bootgrafpred">5.11</a> se pueden observar todas las estimaciones de la media obtenidas a partir de los 1000 remuestreos. Se puede observar que en todos los casos, la máxima velocidad de obtuvo para las células tratadas.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="modelos-no-lineales.html#cb134-1" tabindex="-1"></a>fit.rate<span class="ot">=</span> <span class="cf">function</span>(theta,x){</span>
<span id="cb134-2"><a href="modelos-no-lineales.html#cb134-2" tabindex="-1"></a>  <span class="fu">cbind</span>(theta[<span class="dv">1</span>]<span class="sc">*</span>x<span class="sc">/</span>(theta[<span class="dv">2</span>]<span class="sc">+</span>x),</span>
<span id="cb134-3"><a href="modelos-no-lineales.html#cb134-3" tabindex="-1"></a>        (theta[<span class="dv">1</span>]<span class="sc">+</span>theta[<span class="dv">3</span>])<span class="sc">*</span>x<span class="sc">/</span>(theta[<span class="dv">2</span>]<span class="sc">+</span>theta[<span class="dv">4</span>]<span class="sc">+</span>x))</span>
<span id="cb134-4"><a href="modelos-no-lineales.html#cb134-4" tabindex="-1"></a>}</span>
<span id="cb134-5"><a href="modelos-no-lineales.html#cb134-5" tabindex="-1"></a>x<span class="ot">=</span> <span class="fu">seq</span>(<span class="at">from=</span><span class="dv">0</span>,<span class="at">to=</span><span class="fl">1.1</span>,<span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb134-6"><a href="modelos-no-lineales.html#cb134-6" tabindex="-1"></a></span>
<span id="cb134-7"><a href="modelos-no-lineales.html#cb134-7" tabindex="-1"></a><span class="fu">plot</span>(<span class="cn">NULL</span>,<span class="cn">NULL</span>,<span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">1.1</span>),<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">210</span>),<span class="at">xlab=</span><span class="st">&#39;concentración de sustrato (ppm)&#39;</span>,</span>
<span id="cb134-8"><a href="modelos-no-lineales.html#cb134-8" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&#39;velocidad de reacción&#39;</span>)</span>
<span id="cb134-9"><a href="modelos-no-lineales.html#cb134-9" tabindex="-1"></a>Fit <span class="ot">=</span> <span class="fu">mapply</span>(<span class="cf">function</span>(i){</span>
<span id="cb134-10"><a href="modelos-no-lineales.html#cb134-10" tabindex="-1"></a>  pred <span class="ot">=</span> <span class="fu">fit.rate</span>(mod.boot<span class="sc">$</span>t[i,],x)</span>
<span id="cb134-11"><a href="modelos-no-lineales.html#cb134-11" tabindex="-1"></a>  <span class="fu">lines</span>(x,pred[,<span class="dv">1</span>],<span class="at">col=</span><span class="st">&#39;lightgray&#39;</span>)</span>
<span id="cb134-12"><a href="modelos-no-lineales.html#cb134-12" tabindex="-1"></a>  <span class="fu">lines</span>(x,pred[,<span class="dv">2</span>],<span class="at">col=</span><span class="st">&#39;gray&#39;</span>)</span>
<span id="cb134-13"><a href="modelos-no-lineales.html#cb134-13" tabindex="-1"></a>},<span class="at">i=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>)</span>
<span id="cb134-14"><a href="modelos-no-lineales.html#cb134-14" tabindex="-1"></a><span class="fu">lines</span>(x, thP[<span class="dv">1</span>]<span class="sc">*</span>x<span class="sc">/</span>(thP[<span class="dv">2</span>]<span class="sc">+</span>x),<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb134-15"><a href="modelos-no-lineales.html#cb134-15" tabindex="-1"></a><span class="fu">lines</span>(x, (thP[<span class="dv">1</span>]<span class="sc">+</span>thP[<span class="dv">3</span>])<span class="sc">*</span>x<span class="sc">/</span>(thP[<span class="dv">2</span>]<span class="sc">+</span>thP[<span class="dv">4</span>]<span class="sc">+</span>x))</span>
<span id="cb134-16"><a href="modelos-no-lineales.html#cb134-16" tabindex="-1"></a><span class="fu">points</span>(Puromycin<span class="sc">$</span>conc,Puromycin<span class="sc">$</span>rate,<span class="at">col=</span>Puromycin<span class="sc">$</span>state)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:bootgrafpred"></span>
<img src="MLG2_files/figure-html/bootgrafpred-1.png" alt="Datos puromicina. Curvas medias estimadas por bootstrap. La estimación puntual de la media para las enzimas tratadas es la línea negro y para las enzimas no tratadas es la línea roja." width="672" />
<p class="caption">
Figure 5.11: Datos puromicina. Curvas medias estimadas por bootstrap. La estimación puntual de la media para las enzimas tratadas es la línea negro y para las enzimas no tratadas es la línea roja.
</p>
</div>
</div>
<div id="algunas-consideraciones" class="section level3 hasAnchor" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> Algunas consideraciones<a href="modelos-no-lineales.html#algunas-consideraciones" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Finalmente, algunas consideraciones que se debe de tener a la hora de estimar un modelo no lineal:</p>
<ul>
<li><p>Lo ideal es que el algoritmo llegue a la solución en pocas iteraciones. Esto pasa si la aproximación lineal es adecuada.</p></li>
<li><p>Siempre es bueno evaluar la solución con diferentes puntos iniciales. Es posible que caigamos en un máximo local.</p></li>
<li><p>Si el tamaño de muestra no es grande, las propiedades asintóticas pueden no ser adecuadas. Por lo tanto, es mas conveniente usar bootstrap para hacer inferencias.</p></li>
</ul>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="selección-de-variables.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modelo-lineal-generalizado.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/AlvaroFlorez/MLG2/edit/master/05-ModelosnoLineales.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/AlvaroFlorez/MLG2/blob/master/05-ModelosnoLineales.Rmd",
"text": null
},
"download": ["MLG2.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
