<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 1 Variables indicadoras (o dummies) | Notas de clase: Modelo lineal general II</title>
  <meta name="description" content="Capítulo 1 Variables indicadoras (o dummies) | Notas de clase: Modelo lineal general II" />
  <meta name="generator" content="bookdown 0.33 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 1 Variables indicadoras (o dummies) | Notas de clase: Modelo lineal general II" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 1 Variables indicadoras (o dummies) | Notas de clase: Modelo lineal general II" />
  
  
  

<meta name="author" content="Alvaro J. Flórez" />


<meta name="date" content="2023-05-02" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="modelos-polinomiales.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Notas de clase MLGII</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introducción</a></li>
<li class="chapter" data-level="1" data-path="variables-indicadoras-o-dummies.html"><a href="variables-indicadoras-o-dummies.html"><i class="fa fa-check"></i><b>1</b> Variables indicadoras (o dummies)</a>
<ul>
<li class="chapter" data-level="1.1" data-path="variables-indicadoras-o-dummies.html"><a href="variables-indicadoras-o-dummies.html#ejemplos"><i class="fa fa-check"></i><b>1.1</b> Ejemplos</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="variables-indicadoras-o-dummies.html"><a href="variables-indicadoras-o-dummies.html#datos-de-atletas-australianos"><i class="fa fa-check"></i><b>1.1.1</b> Datos de atletas australianos</a></li>
<li class="chapter" data-level="1.1.2" data-path="variables-indicadoras-o-dummies.html"><a href="variables-indicadoras-o-dummies.html#datos-de-la-onu"><i class="fa fa-check"></i><b>1.1.2</b> Datos de la ONU</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="variables-indicadoras-o-dummies.html"><a href="variables-indicadoras-o-dummies.html#variables-indicadoras"><i class="fa fa-check"></i><b>1.2</b> Variables indicadoras</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="variables-indicadoras-o-dummies.html"><a href="variables-indicadoras-o-dummies.html#modelos-con-covariables-categóricas"><i class="fa fa-check"></i><b>1.2.1</b> Modelos con covariables categóricas</a></li>
<li class="chapter" data-level="1.2.2" data-path="variables-indicadoras-o-dummies.html"><a href="variables-indicadoras-o-dummies.html#modelo-para-los-datos-de-atletas-australianos"><i class="fa fa-check"></i><b>1.2.2</b> Modelo para los datos de atletas australianos</a></li>
<li class="chapter" data-level="1.2.3" data-path="variables-indicadoras-o-dummies.html"><a href="variables-indicadoras-o-dummies.html#modelo-para-los-datos-de-la-onu"><i class="fa fa-check"></i><b>1.2.3</b> Modelo para los datos de la ONU</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html"><i class="fa fa-check"></i><b>2</b> Modelos polinomiales</a>
<ul>
<li class="chapter" data-level="2.1" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#ejemplos-1"><i class="fa fa-check"></i><b>2.1</b> Ejemplos</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#pasteles"><i class="fa fa-check"></i><b>2.1.1</b> Pasteles</a></li>
<li class="chapter" data-level="2.1.2" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#datos-de-boston"><i class="fa fa-check"></i><b>2.1.2</b> Datos de Boston</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#modelos-polinomiales-1"><i class="fa fa-check"></i><b>2.2</b> Modelos polinomiales</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#interpretación-de-los-coeficientes"><i class="fa fa-check"></i><b>2.2.1</b> Interpretación de los coeficientes</a></li>
<li class="chapter" data-level="2.2.2" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#pasteles-1"><i class="fa fa-check"></i><b>2.2.2</b> Pasteles</a></li>
<li class="chapter" data-level="2.2.3" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#datos-de-boston-1"><i class="fa fa-check"></i><b>2.2.3</b> Datos de Boston</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#regresión-por-segmentos"><i class="fa fa-check"></i><b>2.3</b> Regresión por segmentos</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="modelos-polinomiales.html"><a href="modelos-polinomiales.html#ejemplo"><i class="fa fa-check"></i><b>2.3.1</b> Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multicolinealidad.html"><a href="multicolinealidad.html"><i class="fa fa-check"></i><b>3</b> Multicolinealidad</a>
<ul>
<li class="chapter" data-level="3.1" data-path="multicolinealidad.html"><a href="multicolinealidad.html#ejemplos-2"><i class="fa fa-check"></i><b>3.1</b> Ejemplos</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="multicolinealidad.html"><a href="multicolinealidad.html#cemento"><i class="fa fa-check"></i><b>3.1.1</b> Cemento</a></li>
<li class="chapter" data-level="3.1.2" data-path="multicolinealidad.html"><a href="multicolinealidad.html#grasa-corporal"><i class="fa fa-check"></i><b>3.1.2</b> Grasa corporal</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="multicolinealidad.html"><a href="multicolinealidad.html#multicolinealidad-1"><i class="fa fa-check"></i><b>3.2</b> Multicolinealidad</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="multicolinealidad.html"><a href="multicolinealidad.html#causas-de-la-multicolinealidad"><i class="fa fa-check"></i><b>3.2.1</b> Causas de la multicolinealidad</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="multicolinealidad.html"><a href="multicolinealidad.html#detección-de-multicolinealidad"><i class="fa fa-check"></i><b>3.3</b> Detección de multicolinealidad</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="multicolinealidad.html"><a href="multicolinealidad.html#factores-de-inflación-de-varianza"><i class="fa fa-check"></i><b>3.3.1</b> Factores de inflación de varianza</a></li>
<li class="chapter" data-level="3.3.2" data-path="multicolinealidad.html"><a href="multicolinealidad.html#valores-propios-de-boldsymbol-zboldsymbol-z"><i class="fa fa-check"></i><b>3.3.2</b> Valores propios de <span class="math inline">\(\boldsymbol Z&#39;\boldsymbol Z\)</span></a></li>
<li class="chapter" data-level="3.3.3" data-path="multicolinealidad.html"><a href="multicolinealidad.html#valores-singulares-de-boldsymbol-z"><i class="fa fa-check"></i><b>3.3.3</b> Valores singulares de <span class="math inline">\(\boldsymbol Z\)</span></a></li>
<li class="chapter" data-level="3.3.4" data-path="multicolinealidad.html"><a href="multicolinealidad.html#proporciones-de-descomposición-de-varianza"><i class="fa fa-check"></i><b>3.3.4</b> Proporciones de descomposición de varianza</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="multicolinealidad.html"><a href="multicolinealidad.html#datos-de-cemento"><i class="fa fa-check"></i><b>3.4</b> Datos de cemento</a></li>
<li class="chapter" data-level="3.5" data-path="multicolinealidad.html"><a href="multicolinealidad.html#datos-de-grasa-corporal"><i class="fa fa-check"></i><b>3.5</b> Datos de grasa corporal</a></li>
<li class="chapter" data-level="3.6" data-path="multicolinealidad.html"><a href="multicolinealidad.html#solución-al-problema-de-multicolinealidad"><i class="fa fa-check"></i><b>3.6</b> Solución al problema de multicolinealidad</a></li>
<li class="chapter" data-level="3.7" data-path="multicolinealidad.html"><a href="multicolinealidad.html#estimador-de-ridge"><i class="fa fa-check"></i><b>3.7</b> Estimador de ridge</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="multicolinealidad.html"><a href="multicolinealidad.html#datos-de-cemento-1"><i class="fa fa-check"></i><b>3.7.1</b> Datos de cemento</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="multicolinealidad.html"><a href="multicolinealidad.html#estimador-por-componentes-principales"><i class="fa fa-check"></i><b>3.8</b> Estimador por componentes principales</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="multicolinealidad.html"><a href="multicolinealidad.html#datos-de-cemento-2"><i class="fa fa-check"></i><b>3.8.1</b> Datos de cemento</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="selección-de-variables.html"><a href="selección-de-variables.html"><i class="fa fa-check"></i><b>4</b> Selección de variables</a>
<ul>
<li class="chapter" data-level="4.1" data-path="selección-de-variables.html"><a href="selección-de-variables.html#ejemplos-3"><i class="fa fa-check"></i><b>4.1</b> Ejemplos</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="selección-de-variables.html"><a href="selección-de-variables.html#unidad-quirúrgica"><i class="fa fa-check"></i><b>4.1.1</b> Unidad quirúrgica</a></li>
<li class="chapter" data-level="4.1.2" data-path="selección-de-variables.html"><a href="selección-de-variables.html#grasa-corporal-1"><i class="fa fa-check"></i><b>4.1.2</b> Grasa corporal</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="selección-de-variables.html"><a href="selección-de-variables.html#problema-de-selección-de-variables"><i class="fa fa-check"></i><b>4.2</b> Problema de selección de variables</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="selección-de-variables.html"><a href="selección-de-variables.html#qué-pasa-si-ignoramos-covariables-importantes"><i class="fa fa-check"></i><b>4.2.1</b> ¿Qué pasa si ignoramos covariables importantes?</a></li>
<li class="chapter" data-level="4.2.2" data-path="selección-de-variables.html"><a href="selección-de-variables.html#que-pasa-si-incluimos-covariables-irrelevantes"><i class="fa fa-check"></i><b>4.2.2</b> ¿Que pasa si incluimos covariables irrelevantes?</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="selección-de-variables.html"><a href="selección-de-variables.html#métodos-para-la-selección-de-variables"><i class="fa fa-check"></i><b>4.3</b> Métodos para la selección de variables</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="selección-de-variables.html"><a href="selección-de-variables.html#coeficiente-de-determinación"><i class="fa fa-check"></i><b>4.3.1</b> Coeficiente de determinación</a></li>
<li class="chapter" data-level="4.3.2" data-path="selección-de-variables.html"><a href="selección-de-variables.html#coeficiente-de-determinación-ajustado"><i class="fa fa-check"></i><b>4.3.2</b> Coeficiente de determinación ajustado</a></li>
<li class="chapter" data-level="4.3.3" data-path="selección-de-variables.html"><a href="selección-de-variables.html#c_p-de-mallows"><i class="fa fa-check"></i><b>4.3.3</b> C<span class="math inline">\(_p\)</span> de Mallows</a></li>
<li class="chapter" data-level="4.3.4" data-path="selección-de-variables.html"><a href="selección-de-variables.html#estadístico-press"><i class="fa fa-check"></i><b>4.3.4</b> Estadístico PRESS</a></li>
<li class="chapter" data-level="4.3.5" data-path="selección-de-variables.html"><a href="selección-de-variables.html#criterios-de-información"><i class="fa fa-check"></i><b>4.3.5</b> Criterios de información</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="selección-de-variables.html"><a href="selección-de-variables.html#comparación-de-los-modelos"><i class="fa fa-check"></i><b>4.4</b> Comparación de los modelos</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="selección-de-variables.html"><a href="selección-de-variables.html#todos-los-posibles-modelos"><i class="fa fa-check"></i><b>4.4.1</b> Todos los posibles modelos</a></li>
<li class="chapter" data-level="4.4.2" data-path="selección-de-variables.html"><a href="selección-de-variables.html#algorítmos-de-selección"><i class="fa fa-check"></i><b>4.4.2</b> Algorítmos de selección</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="selección-de-variables.html"><a href="selección-de-variables.html#regresión-de-lasso"><i class="fa fa-check"></i><b>4.5</b> Regresión de LASSO</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="selección-de-variables.html"><a href="selección-de-variables.html#datos-de-grasa-corporal-1"><i class="fa fa-check"></i><b>4.5.1</b> Datos de grasa corporal</a></li>
<li class="chapter" data-level="4.5.2" data-path="selección-de-variables.html"><a href="selección-de-variables.html#validación-cruzada"><i class="fa fa-check"></i><b>4.5.2</b> Validación cruzada</a></li>
<li class="chapter" data-level="4.5.3" data-path="selección-de-variables.html"><a href="selección-de-variables.html#ejemplo-grasa-corporal"><i class="fa fa-check"></i><b>4.5.3</b> Ejemplo grasa corporal</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html"><i class="fa fa-check"></i><b>5</b> Modelos no lineales</a>
<ul>
<li class="chapter" data-level="5.1" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#ejemplos-4"><i class="fa fa-check"></i><b>5.1</b> Ejemplos</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#crecimiento-de-pavos"><i class="fa fa-check"></i><b>5.1.1</b> Crecimiento de pavos</a></li>
<li class="chapter" data-level="5.1.2" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#puromicina"><i class="fa fa-check"></i><b>5.1.2</b> Puromicina</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#modelos-no-lineales-1"><i class="fa fa-check"></i><b>5.2</b> Modelos no lineales</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#estimación-de-los-parámetros"><i class="fa fa-check"></i><b>5.2.1</b> Estimación de los parámetros</a></li>
<li class="chapter" data-level="5.2.2" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#inferencia-sobre-los-parámetros"><i class="fa fa-check"></i><b>5.2.2</b> Inferencia sobre los parámetros</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#método-de-bootstrap"><i class="fa fa-check"></i><b>5.3</b> Método de Bootstrap</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#bootstrap-en-regresión"><i class="fa fa-check"></i><b>5.3.1</b> Bootstrap en regresión</a></li>
<li class="chapter" data-level="5.3.2" data-path="modelos-no-lineales.html"><a href="modelos-no-lineales.html#algunas-consideraciones"><i class="fa fa-check"></i><b>5.3.2</b> Algunas consideraciones</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html"><i class="fa fa-check"></i><b>6</b> Modelo lineal generalizado</a>
<ul>
<li class="chapter" data-level="6.1" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#introducción-1"><i class="fa fa-check"></i><b>6.1</b> Introducción</a></li>
<li class="chapter" data-level="6.2" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#casos-de-estudio"><i class="fa fa-check"></i><b>6.2</b> Casos de estudio</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#mortalidad-de-escarabajos"><i class="fa fa-check"></i><b>6.2.1</b> Mortalidad de escarabajos</a></li>
<li class="chapter" data-level="6.2.2" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#ataques-de-epilepsia"><i class="fa fa-check"></i><b>6.2.2</b> ataques de epilepsia</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#preambulo"><i class="fa fa-check"></i><b>6.3</b> Preambulo</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#familia-exponencial"><i class="fa fa-check"></i><b>6.3.1</b> Familia exponencial</a></li>
<li class="chapter" data-level="6.3.2" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#relación-media-varianza"><i class="fa fa-check"></i><b>6.3.2</b> Relación media-varianza:</a></li>
<li class="chapter" data-level="6.3.3" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#estimador-de-máxima-verosimilitud"><i class="fa fa-check"></i><b>6.3.3</b> Estimador de máxima verosimilitud</a></li>
<li class="chapter" data-level="6.3.4" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#métodos-iterativos-de-maximización"><i class="fa fa-check"></i><b>6.3.4</b> Métodos iterativos de maximización</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#modelo-lineal-generalizado-glm"><i class="fa fa-check"></i><b>6.4</b> Modelo lineal generalizado (GLM)</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#componente-aleatorio"><i class="fa fa-check"></i><b>6.4.1</b> Componente aleatorio</a></li>
<li class="chapter" data-level="6.4.2" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#predictor-lineal"><i class="fa fa-check"></i><b>6.4.2</b> Predictor lineal</a></li>
<li class="chapter" data-level="6.4.3" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#función-de-enlace"><i class="fa fa-check"></i><b>6.4.3</b> Función de enlace</a></li>
<li class="chapter" data-level="6.4.4" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#ejemplos-de-glm"><i class="fa fa-check"></i><b>6.4.4</b> Ejemplos de GLM</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#ajuste-de-un-glm"><i class="fa fa-check"></i><b>6.5</b> Ajuste de un GLM</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#especificación-del-modelo"><i class="fa fa-check"></i><b>6.5.1</b> Especificación del modelo</a></li>
<li class="chapter" data-level="6.5.2" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#estimador-por-máxima-verosimilitud-para-boldsymbol-beta"><i class="fa fa-check"></i><b>6.5.2</b> Estimador por máxima verosimilitud para <span class="math inline">\(\boldsymbol \beta\)</span></a></li>
<li class="chapter" data-level="6.5.3" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#interpretación-de-parámetros---modelo-logístico"><i class="fa fa-check"></i><b>6.5.3</b> interpretación de parámetros - modelo logístico</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#pruebas-de-hipótesis"><i class="fa fa-check"></i><b>6.6</b> Pruebas de hipótesis</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#método-de-razón-de-verosimilitud"><i class="fa fa-check"></i><b>6.6.1</b> Método de razón de verosimilitud</a></li>
<li class="chapter" data-level="6.6.2" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#método-de-wald"><i class="fa fa-check"></i><b>6.6.2</b> Método de Wald</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#intervalos-de-confianza"><i class="fa fa-check"></i><b>6.7</b> intervalos de confianza</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#intervalo-de-confianza-para-la-media"><i class="fa fa-check"></i><b>6.7.1</b> Intervalo de confianza para la media</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#devianza"><i class="fa fa-check"></i><b>6.8</b> Devianza</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#el-estadístico-chi-cuadrado-de-pearson"><i class="fa fa-check"></i><b>6.8.1</b> El estadístico chi-cuadrado de Pearson</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#bondad-de-ajuste"><i class="fa fa-check"></i><b>6.9</b> Bondad de ajuste</a></li>
<li class="chapter" data-level="6.10" data-path="modelo-lineal-generalizado.html"><a href="modelo-lineal-generalizado.html#selección-de-variables-1"><i class="fa fa-check"></i><b>6.10</b> Selección de variables</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="modelo-logístico.html"><a href="modelo-logístico.html"><i class="fa fa-check"></i><b>7</b> Modelo logístico</a>
<ul>
<li class="chapter" data-level="7.1" data-path="modelo-logístico.html"><a href="modelo-logístico.html#casos-de-estudio-1"><i class="fa fa-check"></i><b>7.1</b> Casos de estudio</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="modelo-logístico.html"><a href="modelo-logístico.html#mortalidad-de-escarabajos-1"><i class="fa fa-check"></i><b>7.1.1</b> Mortalidad de escarabajos</a></li>
<li class="chapter" data-level="7.1.2" data-path="modelo-logístico.html"><a href="modelo-logístico.html#bajo-peso-al-nacer"><i class="fa fa-check"></i><b>7.1.2</b> Bajo peso al nacer</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="modelo-logístico.html"><a href="modelo-logístico.html#datos-agrupados-o-datos-no-agrupados"><i class="fa fa-check"></i><b>7.2</b> Datos agrupados o datos no agrupados</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="modelo-logístico.html"><a href="modelo-logístico.html#datos-agrupados"><i class="fa fa-check"></i><b>7.2.1</b> Datos agrupados</a></li>
<li class="chapter" data-level="7.2.2" data-path="modelo-logístico.html"><a href="modelo-logístico.html#datos-no-agrupados"><i class="fa fa-check"></i><b>7.2.2</b> Datos no agrupados</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="modelo-logístico.html"><a href="modelo-logístico.html#funciones-de-enlace"><i class="fa fa-check"></i><b>7.3</b> Funciones de enlace</a></li>
<li class="chapter" data-level="7.4" data-path="modelo-logístico.html"><a href="modelo-logístico.html#curva-característica-operativa-del-receptorroc"><i class="fa fa-check"></i><b>7.4</b> Curva característica operativa del receptor(ROC)</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="modelo-logístico.html"><a href="modelo-logístico.html#ejemplo-mortalidad-de-escarabajos-1"><i class="fa fa-check"></i><b>7.4.1</b> Ejemplo mortalidad de escarabajos</a></li>
<li class="chapter" data-level="7.4.2" data-path="modelo-logístico.html"><a href="modelo-logístico.html#bajo-peso-al-nacer-1"><i class="fa fa-check"></i><b>7.4.2</b> Bajo peso al nacer</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="modelo-logístico.html"><a href="modelo-logístico.html#sobredispersión"><i class="fa fa-check"></i><b>7.5</b> Sobredispersión</a></li>
<li class="chapter" data-level="7.6" data-path="modelo-logístico.html"><a href="modelo-logístico.html#distribución-beta-binomial"><i class="fa fa-check"></i><b>7.6</b> Distribución beta-binomial</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="modelo-logístico.html"><a href="modelo-logístico.html#modelo-beta-binomial"><i class="fa fa-check"></i><b>7.6.1</b> Modelo beta-binomial</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html"><i class="fa fa-check"></i><b>8</b> Modelo para conteos</a>
<ul>
<li class="chapter" data-level="8.1" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#casos-de-estudio-2"><i class="fa fa-check"></i><b>8.1</b> Casos de estudio</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#ataques-de-epilepsia-1"><i class="fa fa-check"></i><b>8.1.1</b> Ataques de epilepsia</a></li>
<li class="chapter" data-level="8.1.2" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#datos-de-cáncer-de-pulmón"><i class="fa fa-check"></i><b>8.1.2</b> Datos de cáncer de pulmón</a></li>
<li class="chapter" data-level="8.1.3" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#número-de-cangrejos-satélites"><i class="fa fa-check"></i><b>8.1.3</b> Número de cangrejos satélites</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#modelo-poisson"><i class="fa fa-check"></i><b>8.2</b> Modelo Poisson</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#modelo-de-conteo-con-offset"><i class="fa fa-check"></i><b>8.2.1</b> Modelo de conteo con offset</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#distribución-binomial-negativa"><i class="fa fa-check"></i><b>8.3</b> Distribución binomial negativa</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#modelo-binomial-negativo-poisson-gamma"><i class="fa fa-check"></i><b>8.3.1</b> Modelo binomial negativo (Poisson-gamma)</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#modelo-poisson-con-ceros-inflados"><i class="fa fa-check"></i><b>8.4</b> Modelo Poisson con ceros inflados</a></li>
<li class="chapter" data-level="8.5" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#modelo-hurdle"><i class="fa fa-check"></i><b>8.5</b> Modelo Hurdle</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="modelo-para-conteos.html"><a href="modelo-para-conteos.html#número-de-cangrejos-satélites-1"><i class="fa fa-check"></i><b>8.5.1</b> Número de cangrejos satélites</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html"><i class="fa fa-check"></i><b>9</b> Modelo lineal mixto</a>
<ul>
<li class="chapter" data-level="9.1" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html#casos-de-estudio-3"><i class="fa fa-check"></i><b>9.1</b> Casos de estudio</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html#peso-al-nacer-de-corderos"><i class="fa fa-check"></i><b>9.1.1</b> Peso al nacer de corderos</a></li>
<li class="chapter" data-level="9.1.2" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html#crecimiento-craneofacial-de-ratas"><i class="fa fa-check"></i><b>9.1.2</b> Crecimiento craneofacial de ratas</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html#datos-correlacionados"><i class="fa fa-check"></i><b>9.2</b> Datos correlacionados</a></li>
<li class="chapter" data-level="9.3" data-path="modelo-lineal-mixto.html"><a href="modelo-lineal-mixto.html#modelo-lineal-mixto-1"><i class="fa fa-check"></i><b>9.3</b> Modelo lineal mixto</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Notas de clase: Modelo lineal general II</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="variables-indicadoras-o-dummies" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Capítulo 1</span> Variables indicadoras (o dummies)<a href="variables-indicadoras-o-dummies.html#variables-indicadoras-o-dummies" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="ejemplos" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Ejemplos<a href="variables-indicadoras-o-dummies.html#ejemplos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="datos-de-atletas-australianos" class="section level3 hasAnchor" number="1.1.1">
<h3><span class="header-section-number">1.1.1</span> Datos de atletas australianos<a href="variables-indicadoras-o-dummies.html#datos-de-atletas-australianos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Los datos <code>ais</code> de la libreria <code>alr4</code> tiene información sobre 202 atletas de élite de Australia (102 hombres y 100 mujeres). Se quiere evaluar la relación entre la concentración de hemoglobina (<code>Hg</code>, g/dl) y el índice de masa corporal (<code>BMI</code>, kg/m<span class="math inline">\(^2\)</span>).</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="variables-indicadoras-o-dummies.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(ais)</span>
<span id="cb1-2"><a href="variables-indicadoras-o-dummies.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb1-3"><a href="variables-indicadoras-o-dummies.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(ais<span class="sc">$</span>Hg[ais<span class="sc">$</span>Sex<span class="sc">==</span><span class="dv">0</span>]),<span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">11</span>,<span class="dv">20</span>),<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">main =</span> <span class="st">&#39;&#39;</span>,<span class="at">ylab=</span><span class="st">&#39;Densidad&#39;</span>,<span class="at">xlab=</span><span class="st">&#39;Hg (g/dl)&#39;</span>)</span>
<span id="cb1-4"><a href="variables-indicadoras-o-dummies.html#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(ais<span class="sc">$</span>Hg[ais<span class="sc">$</span>Sex<span class="sc">==</span><span class="dv">1</span>]),<span class="at">col=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb1-5"><a href="variables-indicadoras-o-dummies.html#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Hg<span class="sc">~</span>BMI,<span class="at">data=</span>ais,<span class="at">col=</span>ais<span class="sc">$</span>Sex<span class="sc">+</span><span class="dv">1</span>,<span class="at">ylab=</span><span class="st">&#39;Hg (g/dl)&#39;</span>,<span class="at">xlab=</span><span class="st">&#39;BMI&#39;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:AtletesFigure"></span>
<img src="MLG2_files/figure-html/AtletesFigure-1.png" alt="Datos de atletas. Densidad de la hemoglobina para hombres y mujeres (derecha) y diagrama de dispersión entre la homoglobina y el índice de masa corporal (izquierda). Negro para hombres y rojo para mujeres." width="576" />
<p class="caption">
Figure 1.1: Datos de atletas. Densidad de la hemoglobina para hombres y mujeres (derecha) y diagrama de dispersión entre la homoglobina y el índice de masa corporal (izquierda). Negro para hombres y rojo para mujeres.
</p>
</div>
<p>En la Figura <a href="variables-indicadoras-o-dummies.html#fig:AtletesFigure">1.1</a> (izquierda) vemos que los niveles de hemoglobina son mayores para hombres que para mujeres. En la Figura <a href="variables-indicadoras-o-dummies.html#fig:AtletesFigure">1.1</a> (derecha) observamos que hay una relación positiva entre la hemoglobina y el índice de masa corporal tanto para hombres como para mujeres. Esto nos puede indicar que ingresar el sexo del atleta en el modelo puede mejorarnos el ajuste.</p>
</div>
<div id="datos-de-la-onu" class="section level3 hasAnchor" number="1.1.2">
<h3><span class="header-section-number">1.1.2</span> Datos de la ONU<a href="variables-indicadoras-o-dummies.html#datos-de-la-onu" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Retomemos los datos de la ONU (<code>UN11</code> de la librería <code>alr4</code>). Las variables de interés son:</p>
<ul>
<li><strong>fertility</strong>: Número esperado de nacidos vivos por mujer.</li>
<li><strong>ppgdp</strong>: producto nacional bruto per cápita (PNB, en dólares).</li>
<li><strong>Purban</strong>: el porcentaje de la población que vive en un área urbana.</li>
<li><strong>lifeExpF</strong>: esperanza de vida femenina (años).</li>
<li><strong>group</strong>: si el país pertenece a la OCDE (Organización para la Cooperación y el Desarrollo Económicos), África o otros.</li>
</ul>
<p>Por ahora consideremos la relación entre la fertilidad y el PNB per cápita, teniendo en cuenta el grupo al que pertenece cada país.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="variables-indicadoras-o-dummies.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(UN11)</span>
<span id="cb2-2"><a href="variables-indicadoras-o-dummies.html#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">log</span>(fertility)<span class="sc">~</span><span class="fu">log</span>(ppgdp),<span class="at">data=</span>UN11,<span class="at">col=</span>UN11<span class="sc">$</span>group,<span class="at">xlab=</span><span class="st">&#39;log PNB per cápita (dólares)&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;log # esperado de nacidos vivos por mujer&#39;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:UN11Figure"></span>
<img src="MLG2_files/figure-html/UN11Figure-1.png" alt="Datos de la ONU. Relación entre la fertilidad y el PNB per cápita para los países de OCDE (puntos negros), países africanos (puntos verdes) y los otros países (rojos)" width="576" />
<p class="caption">
Figure 1.2: Datos de la ONU. Relación entre la fertilidad y el PNB per cápita para los países de OCDE (puntos negros), países africanos (puntos verdes) y los otros países (rojos)
</p>
</div>
<p>En la Figura <a href="variables-indicadoras-o-dummies.html#fig:UN11Figure">1.2</a> podemos observar que, en general, cuando el PNB aumenta, la tasa de fertilidad disminuye. Sin embargo, esta relación puede variar según la categoría del país. Para los países de la OCDE, esta relación no es fuerte. Mientras que para los demás se mantiene esta relación negativa. Por esta razón sería de gran importancia incluir esta variable categórica dentro del modelo.</p>
</div>
</div>
<div id="variables-indicadoras" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Variables indicadoras<a href="variables-indicadoras-o-dummies.html#variables-indicadoras" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Las covariables categóricas entran en un modelo como variables indicadoras (o también llamadas <em>dummies</em>). En el caso que la covariable <span class="math inline">\((X)\)</span> tenga dos categorías, entonces se crea una variable indicadora. Por ejemplo, para los datos de los atletas, el sexo requiere una indicadora:
<span class="math display">\[
u_{i} = \begin{cases}
1 &amp; \mbox{ si la observación i es hombre}, \\
0 &amp; \mbox{ si la observación i es mujer}. \\
\end{cases}
\]</span>
Aquí mujer es llamada la categoría de referencia.</p>
<p>En caso que la covariable categórica tenga <span class="math inline">\(k\)</span> categorías, se tienen que crear <span class="math inline">\(k-1\)</span> variables indicadoras. Por ejemplo, para la variable grupo de país en los datos de la ONU se requieren 2 variables indicadoras <span class="math inline">\((u_{j})\)</span> como lo muestra la Tabla <a href="variables-indicadoras-o-dummies.html#tab:dosIndica">1.1</a>.</p>
<table>
<caption>
<span id="tab:dosIndica">Table 1.1: </span>Variables indicadoras para la variable <code>group</code> de los datos de la ONU
</caption>
<thead>
<tr>
<th style="text-align:left;">
Categoría
</th>
<th style="text-align:right;">
<span class="math inline">\(u_{1}\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(u_{2}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
OECD
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
otro
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
África
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
</tr>
</tbody>
</table>
<div id="modelos-con-covariables-categóricas" class="section level3 hasAnchor" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> Modelos con covariables categóricas<a href="variables-indicadoras-o-dummies.html#modelos-con-covariables-categóricas" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suponga que se quiere ajustar un modelo para una variable respuesta <span class="math inline">\(Y\)</span> en función de dos covariables: una continua <span class="math inline">\(X\)</span> y una indicadora <span class="math inline">\(Z\)</span> (es decir una variable categórica con dos 2 categorías). El modelo propuesto es el siguiente:
<span class="math display" id="eq:modInter">\[\begin{equation}
y_{i}  = \beta_{0} + x_{i}\beta_{1} + z_{i}\beta_{2} + x_{i}z_{i}\beta_{3} + \varepsilon_{i},
\tag{1.1}
\end{equation}\]</span>
donde <span class="math inline">\(\varepsilon_{i} \sim N(0,\sigma^{2})\)</span>.</p>
<p>Tenemos que, si <span class="math inline">\(z_i=0\)</span>:
<span class="math display">\[
E(Y | X=x_i, Z=0) = \beta_{0} + x_{i}\beta_{1}.
\]</span>
Mientras que, si <span class="math inline">\(z_i=1\)</span>:
<span class="math display">\[
E(Y | X=x_i, Z=1) = (\beta_{0}+\beta_{2}) + x_{i}(\beta_{1}+\beta_{3}).
\]</span>
Por lo que el modelo <a href="variables-indicadoras-o-dummies.html#eq:modInter">(1.1)</a> genera dos rectas, una para cada categoría. <span class="math inline">\(\beta_2\)</span> indica la diferencia de intercepto entre las dos categorías y <span class="math inline">\(\beta_3\)</span> la diferencia entre pendientes. En la Figura <a href="variables-indicadoras-o-dummies.html#fig:Rectas1">1.3</a>(izquierda) se observan las dos rectas que se obtienen a partir de este modelo. Si se elimina la interacción entre variables, se obtienen dos rectas paralelas (Figura <a href="variables-indicadoras-o-dummies.html#fig:Rectas1">1.3</a>, derecha).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Rectas1"></span>
<img src="MLG2_files/figure-html/Rectas1-1.png" alt="Efecto de la interacción entre variable continua e indicadora. Modelo general (izquierda) y modelo de líneas paralelas (derecha)." width="864" />
<p class="caption">
Figure 1.3: Efecto de la interacción entre variable continua e indicadora. Modelo general (izquierda) y modelo de líneas paralelas (derecha).
</p>
</div>
</div>
<div id="modelo-para-los-datos-de-atletas-australianos" class="section level3 hasAnchor" number="1.2.2">
<h3><span class="header-section-number">1.2.2</span> Modelo para los datos de atletas australianos<a href="variables-indicadoras-o-dummies.html#modelo-para-los-datos-de-atletas-australianos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para los datos de los atletas, se sugiere el siguiente modelo:
<span class="math display">\[\begin{equation}
\begin{split}
\mbox{Hg}_{i} =&amp; \beta_{0} + \mbox{Sex}_{i}\beta_{1} + \mbox{BMI}_{i}\beta_{2} + \mbox{Sex}_{i}\mbox{BMI}_{i}\beta_{3} + \varepsilon_{i},
\end{split}
\nonumber
\end{equation}\]</span>
donde:
<span class="math display">\[
\mbox{Sex}_{i} = \begin{cases}
1 &amp; \mbox{ si la observación i corresponde a una mujer}, \\
0 &amp; \mbox{ de otra forma}. \\
\end{cases}
\]</span>
Note que en la base de datos <code>ais</code>, la variable <code>sex</code> ya está codificada de esta forma. Si la variable no está codificada de forma numérica, <code>R</code> eligirá la categoría de referencia de forma automática.</p>
<p>Para ajustar el modelo utilizamos la función <code>lm</code> (aquí estamos incluyendo los efectos de <code>BMI</code> y <code>Sex</code>, así como la interacción):</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="variables-indicadoras-o-dummies.html#cb3-1" aria-hidden="true" tabindex="-1"></a>mod.ais <span class="ot">=</span> <span class="fu">lm</span>(Hg<span class="sc">~</span>Sex<span class="sc">*</span>BMI, <span class="at">data=</span>ais)</span>
<span id="cb3-2"><a href="variables-indicadoras-o-dummies.html#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod.ais)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Hg ~ Sex * BMI, data = ais)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.9997 -0.6625 -0.0478  0.5784  3.5583 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 13.21316    0.78662  16.797   &lt;2e-16 ***
## Sex         -0.66140    1.09835  -0.602   0.5477    
## BMI          0.09788    0.03269   2.994   0.0031 ** 
## Sex:BMI     -0.05203    0.04761  -1.093   0.2758    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9092 on 198 degrees of freedom
## Multiple R-squared:  0.5613, Adjusted R-squared:  0.5546 
## F-statistic: 84.44 on 3 and 198 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Tenemos que <span class="math inline">\(\widehat{\beta}_{2} =0.1\)</span>, lo que nos indica que el valor esperado del nivel de hemoglobina aumenta en <span class="math inline">\(0.1\)</span> g/dl por cada aumento unitario en el índice de masa corporal de los hombres. Para las mujeres, el efecto del índice de masa corporal sobre el nivel de hemoglobina también es positivo, pero con una pendiente menor <span class="math inline">\(\widehat{\beta}_{2} +\widehat{\beta}_{3} = 0.1 - 0.05 = 0.05\)</span>.</p>
<p>La representación gráfica del modelo se puede observar en la Figura <a href="variables-indicadoras-o-dummies.html#fig:AtletesAjuste">1.4</a>. Aquí vemos que la pendiente para las mujeres es un poco menor que para los hombres.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="variables-indicadoras-o-dummies.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Hg<span class="sc">~</span>BMI,<span class="at">data=</span>ais,<span class="at">col=</span>ais<span class="sc">$</span>Sex<span class="sc">+</span><span class="dv">1</span>,<span class="at">ylab=</span><span class="st">&#39;Hg (g/dl)&#39;</span>,<span class="at">xlab=</span><span class="st">&#39;BMI&#39;</span>)</span>
<span id="cb5-2"><a href="variables-indicadoras-o-dummies.html#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span>mod.ais<span class="sc">$</span>coefficients[<span class="dv">1</span>],<span class="at">b=</span>mod.ais<span class="sc">$</span>coefficients[<span class="dv">3</span>],<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb5-3"><a href="variables-indicadoras-o-dummies.html#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span>mod.ais<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>mod.ais<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">b=</span>mod.ais<span class="sc">$</span>coefficients[<span class="dv">3</span>]<span class="sc">+</span>mod.ais<span class="sc">$</span>coefficients[<span class="dv">4</span>],<span class="at">col=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:AtletesAjuste"></span>
<img src="MLG2_files/figure-html/AtletesAjuste-1.png" alt="Datos de atletas. Ajuste del modelo para la homoglobina en función  del índice de masa corporal y sexo. Línea negra para hombres y línea roja para mujeres." width="576" />
<p class="caption">
Figure 1.4: Datos de atletas. Ajuste del modelo para la homoglobina en función del índice de masa corporal y sexo. Línea negra para hombres y línea roja para mujeres.
</p>
</div>
<p>Si miramos la significancia del <span class="math inline">\(\widehat{\beta}_3\)</span> (valor-<span class="math inline">\(p\)</span> igual a 0.276), podemos concluir que las diferencias en pendiente no son significativas. Por lo que, el efecto del índice de masa corporal sobre los niveles de hemoglobina es el mismo para mujeres que para hombres.</p>
<p>Si queremos evaluar si los niveles de hemoglobina son iguales para hombres y mujeres, debemos evaluar la siguiente hipótesis:
<span class="math display">\[
H_{0}: \beta_{1} = \beta_3 = 0.
\]</span>
En <code>R</code>, esto lo podemos realizar usando la función <code>anova()</code> (prueba F) comparando el modelo completo contra el modelo reducido sin la variable <code>Sex</code>:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="variables-indicadoras-o-dummies.html#cb6-1" aria-hidden="true" tabindex="-1"></a>mod.ais.red <span class="ot">=</span> <span class="fu">lm</span>(Hg<span class="sc">~</span>BMI, <span class="at">data=</span>ais)</span>
<span id="cb6-2"><a href="variables-indicadoras-o-dummies.html#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod.ais.red,mod.ais)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Hg ~ BMI
## Model 2: Hg ~ Sex * BMI
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    200 318.52                                  
## 2    198 163.69  2    154.82 93.637 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Vemos que se rechaza <span class="math inline">\(H_0\)</span>, es decir que hay diferencias en los niveles de homoglobina entre hombres y mujeres. <span class="math inline">\(\beta_1\)</span> o <span class="math inline">\(\beta_3\)</span> es diferente de cero, pero no ambos (esto por los resultados del modelo completo).</p>
<p>Eliminando la interacción obtenemos un modelo con lineas paralelas:
<span class="math display">\[
\mbox{Hg}_{i} = \beta_{0} + \mbox{Sex}_{i}\beta_{1} + \mbox{BMI}_{i}\beta_{2} +  \varepsilon_{i},
\]</span>
donde <span class="math inline">\(\varepsilon_{i} \sim N(0, \sigma^{2})\)</span>, y se calcula de la siguiente forma:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="variables-indicadoras-o-dummies.html#cb8-1" aria-hidden="true" tabindex="-1"></a>mod.ais.lp <span class="ot">=</span> <span class="fu">lm</span>(Hg<span class="sc">~</span>Sex<span class="sc">+</span>BMI, <span class="at">data=</span>ais)</span>
<span id="cb8-2"><a href="variables-indicadoras-o-dummies.html#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod.ais.lp)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Hg ~ Sex + BMI, data = ais)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.0131 -0.6530 -0.0263  0.6249  3.5806 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 13.79954    0.57549  23.979  &lt; 2e-16 ***
## Sex         -1.85251    0.13587 -13.634  &lt; 2e-16 ***
## BMI          0.07335    0.02378   3.085  0.00233 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9097 on 199 degrees of freedom
## Multiple R-squared:  0.5586, Adjusted R-squared:  0.5542 
## F-statistic: 125.9 on 2 and 199 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>La estimación del efecto asociado al sexo indica la diferencia media del nivel de hemoglobina entre hombres y mujeres. En la Figura <a href="variables-indicadoras-o-dummies.html#fig:AtletesAjuste2">1.5</a> vemos que el modelo de líneas paralelas tiene casi el mismo ajuste que el modelo general.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="variables-indicadoras-o-dummies.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Hg<span class="sc">~</span>BMI,<span class="at">data=</span>ais,<span class="at">col=</span>ais<span class="sc">$</span>Sex<span class="sc">+</span><span class="dv">1</span>,<span class="at">ylab=</span><span class="st">&#39;Hg (g/dl)&#39;</span>,<span class="at">xlab=</span><span class="st">&#39;BMI&#39;</span>)</span>
<span id="cb10-2"><a href="variables-indicadoras-o-dummies.html#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span>mod.ais<span class="sc">$</span>coefficients[<span class="dv">1</span>],<span class="at">b=</span>mod.ais<span class="sc">$</span>coefficients[<span class="dv">3</span>],<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb10-3"><a href="variables-indicadoras-o-dummies.html#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span>mod.ais<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>mod.ais<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">b=</span>mod.ais<span class="sc">$</span>coefficients[<span class="dv">3</span>]<span class="sc">+</span>mod.ais<span class="sc">$</span>coefficients[<span class="dv">4</span>],<span class="at">col=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb10-4"><a href="variables-indicadoras-o-dummies.html#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span>mod.ais.lp<span class="sc">$</span>coefficients[<span class="dv">1</span>],<span class="at">b=</span>mod.ais.lp<span class="sc">$</span>coefficients[<span class="dv">3</span>],<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb10-5"><a href="variables-indicadoras-o-dummies.html#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span>mod.ais.lp<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">+</span>mod.ais.lp<span class="sc">$</span>coefficients[<span class="dv">2</span>],<span class="at">b=</span>mod.ais.lp<span class="sc">$</span>coefficients[<span class="dv">3</span>],<span class="at">col=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:AtletesAjuste2"></span>
<img src="MLG2_files/figure-html/AtletesAjuste2-1.png" alt="Datos de atletas. Ajuste del modelo general (línea solida) y el modelo líneas paralelas (línea discontinua) para la homoglobina en función  del índice de masa corporal y sexo. Líneas negra para hombres y líneas roja para mujeres." width="576" />
<p class="caption">
Figure 1.5: Datos de atletas. Ajuste del modelo general (línea solida) y el modelo líneas paralelas (línea discontinua) para la homoglobina en función del índice de masa corporal y sexo. Líneas negra para hombres y líneas roja para mujeres.
</p>
</div>
<p>En conclusión, hay diferencia en los niveles de hemoglobina entre hombres y mujeres (es, en promedio, mayor para lo hombres en 1.85g/dl). Sin embargo, el efecto del índice de masa corporal es el mismo para ambos sexos.</p>
</div>
<div id="modelo-para-los-datos-de-la-onu" class="section level3 hasAnchor" number="1.2.3">
<h3><span class="header-section-number">1.2.3</span> Modelo para los datos de la ONU<a href="variables-indicadoras-o-dummies.html#modelo-para-los-datos-de-la-onu" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El modelo propuesto es el siguiente:
<span class="math display">\[\begin{equation}
\begin{split}
\log\mbox{fertility}_{i} =&amp; \beta_{0} + \mbox{u}_{1i}\beta_{1}+\mbox{u}_{2i}\beta_{2} + \log\mbox{ppgdp}_{i}\beta_{3} + \\ &amp; \mbox{u}_{1i}\log\mbox{ppgdp}_{i}\beta_{4} + \mbox{u}_{2i}\log\mbox{ppgdp}_{i}\beta_{5} + \varepsilon_{i},
\end{split}
\nonumber
\end{equation}\]</span>
donde:
<span class="math display">\[
\mbox{u}_{1i} = \begin{cases}
1 &amp; \mbox{ si el país i pertenece a la categoría otro}, \\
0 &amp; \mbox{ de otra forma}, \\
\end{cases}  \mbox{ y }
\mbox{u}_{2i} = \begin{cases}
1 &amp; \mbox{ si el país i pertenece a África}, \\
0 &amp; \mbox{ de otra forma}. \\
\end{cases}
\]</span>
Por lo tanto, OECD es la categoría de referencia.</p>
<p>El modelo ajustado es:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="variables-indicadoras-o-dummies.html#cb11-1" aria-hidden="true" tabindex="-1"></a>mod.UN11 <span class="ot">=</span> <span class="fu">lm</span>(<span class="fu">log</span>(fertility)<span class="sc">~</span>group<span class="sc">*</span><span class="fu">log</span>(ppgdp), <span class="at">data=</span>UN11)</span>
<span id="cb11-2"><a href="variables-indicadoras-o-dummies.html#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod.UN11)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(fertility) ~ group * log(ppgdp), data = UN11)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.69358 -0.16963  0.02005  0.16838  0.73633 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)             0.21836    0.81290   0.269  0.78851   
## groupother              1.87888    0.83290   2.256  0.02520 * 
## groupafrica             2.54072    0.84299   3.014  0.00293 **
## log(ppgdp)              0.03217    0.07832   0.411  0.68170   
## groupother:log(ppgdp)  -0.18418    0.08106  -2.272  0.02417 * 
## groupafrica:log(ppgdp) -0.22637    0.08430  -2.685  0.00788 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2739 on 193 degrees of freedom
## Multiple R-squared:  0.6305, Adjusted R-squared:  0.6209 
## F-statistic: 65.86 on 5 and 193 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>A partir de estos resultados obtenemos tres rectas que describen el valor esperado del logarítmo de la fertilidad en función del logarítmo del PNB per cápita, una para cada tipo de país. Para los países de la OCDE, tenemos que:
<span class="math display">\[
E(\log\mbox{fertility}) = 0.218 + 0.032\log \mbox{ppgdp}.
\]</span>
Para los países Africanos:
<span class="math display">\[
E(\log\mbox{fertility}) = 2.759  -0.194\log \mbox{ppgdp}.
\]</span>
Finalmente, para los otros países:
<span class="math display">\[
E(\log\mbox{fertility}) = 2.097  -0.152\log \mbox{ppgdp}.
\]</span>
Aquí vemos que para los países que no son de la OCDE, el PNB tiene un efecto negativo significativo sobre la tasa de fertilidad. Mientras que para los países de la OCDE, este efecto es positivo, aunque no es significativo. Esto mismo lo podemos ver gráficamente en la Figura <a href="variables-indicadoras-o-dummies.html#fig:MCOUN11Figure">1.6</a>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="variables-indicadoras-o-dummies.html#cb13-1" aria-hidden="true" tabindex="-1"></a>Beta.UN11 <span class="ot">=</span> mod.UN11<span class="sc">$</span>coefficients</span>
<span id="cb13-2"><a href="variables-indicadoras-o-dummies.html#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">log</span>(fertility)<span class="sc">~</span><span class="fu">log</span>(ppgdp),<span class="at">data=</span>UN11,<span class="at">col=</span>UN11<span class="sc">$</span>group,<span class="at">xlab=</span><span class="st">&#39;log PNB per cápita (dólares)&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;log # esperado de nacidos vivos por mujer&#39;</span>)</span>
<span id="cb13-3"><a href="variables-indicadoras-o-dummies.html#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span>Beta.UN11[<span class="dv">1</span>],<span class="at">b=</span>Beta.UN11[<span class="dv">4</span>],<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb13-4"><a href="variables-indicadoras-o-dummies.html#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span>Beta.UN11[<span class="dv">1</span>]<span class="sc">+</span>Beta.UN11[<span class="dv">2</span>],<span class="at">b=</span>Beta.UN11[<span class="dv">4</span>]<span class="sc">+</span>Beta.UN11[<span class="dv">5</span>],<span class="at">col=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb13-5"><a href="variables-indicadoras-o-dummies.html#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span>Beta.UN11[<span class="dv">1</span>]<span class="sc">+</span>Beta.UN11[<span class="dv">3</span>],<span class="at">b=</span>Beta.UN11[<span class="dv">4</span>]<span class="sc">+</span>Beta.UN11[<span class="dv">6</span>],<span class="at">col=</span><span class="dv">3</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:MCOUN11Figure"></span>
<img src="MLG2_files/figure-html/MCOUN11Figure-1.png" alt="Datos de la ONU. Ajuste del modelo para la fertilidad en función  del PNB y tipo de país. Países de OCDE (línea negra), países africanos (línea verde) y los otros países (línea roja)" width="576" />
<p class="caption">
Figure 1.6: Datos de la ONU. Ajuste del modelo para la fertilidad en función del PNB y tipo de país. Países de OCDE (línea negra), países africanos (línea verde) y los otros países (línea roja)
</p>
</div>
<p>Usando la función <code>relevel()</code> se puede cambiar la categoría de referencia. Por ejemplo, si queremos que la categoría de referencia sea <code>other</code>:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="variables-indicadoras-o-dummies.html#cb14-1" aria-hidden="true" tabindex="-1"></a>UN11.alt <span class="ot">=</span> UN11</span>
<span id="cb14-2"><a href="variables-indicadoras-o-dummies.html#cb14-2" aria-hidden="true" tabindex="-1"></a>UN11.alt<span class="sc">$</span>group <span class="ot">=</span>  <span class="fu">relevel</span>(UN11.alt<span class="sc">$</span>group,<span class="at">ref =</span><span class="st">&#39;other&#39;</span>)</span>
<span id="cb14-3"><a href="variables-indicadoras-o-dummies.html#cb14-3" aria-hidden="true" tabindex="-1"></a>mod.UN11.alt <span class="ot">=</span> <span class="fu">lm</span>(<span class="fu">log</span>(fertility)<span class="sc">~</span>group<span class="sc">*</span><span class="fu">log</span>(ppgdp), <span class="at">data=</span>UN11.alt)</span>
<span id="cb14-4"><a href="variables-indicadoras-o-dummies.html#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod.UN11.alt)</span></code></pre></div>
<p>Note que cambiar la categoría de referencia no altera en nada los resultados del ajuste. Solo cambian la interpretación de los coeficientes.</p>
<p>Se podría hacer la siguiente pregunta, ¿el efecto del PNB sobre la fertilidad es el mismo para cada tipo de país?. Para resolver esta pregunta, se plantea la siguiente hipótesis:
<span class="math display">\[
H_0: \beta_4 = \beta_5 = 0.
\]</span>
El estadístico de prueba lo podemos obtener usando la función <code>anova()</code> (prueba F) en R:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="variables-indicadoras-o-dummies.html#cb15-1" aria-hidden="true" tabindex="-1"></a>mod.UN11.red <span class="ot">=</span> <span class="fu">lm</span>(<span class="fu">log</span>(fertility)<span class="sc">~</span>group<span class="sc">+</span><span class="fu">log</span>(ppgdp), <span class="at">data=</span>UN11)</span>
<span id="cb15-2"><a href="variables-indicadoras-o-dummies.html#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod.UN11.red,mod.UN11)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: log(fertility) ~ group + log(ppgdp)
## Model 2: log(fertility) ~ group * log(ppgdp)
##   Res.Df    RSS Df Sum of Sq      F  Pr(&gt;F)  
## 1    195 15.033                              
## 2    193 14.484  2   0.54848 3.6542 0.02769 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Este resultado indica que hay evidencia suficiente para concluir que el efecto del PNB sobre la fertilidad no es el mismo para cada tipo de país.</p>
<p>Ahora, podríamos preguntarnos: ¿las pendientes son las mismas para las categorías de otro y África?. Para esto, se plantea la siguiente hipótesis:
<span class="math display">\[
H_0: \beta_4 = \beta_5.
\]</span>
También se puede expresar de la siguiente forma:
<span class="math display">\[
H_{0}: \boldsymbol L\boldsymbol \beta= \begin{pmatrix}
0 &amp; 0 &amp; 0 &amp; 0 &amp; 1 &amp; -1
\end{pmatrix} \begin{pmatrix}
\beta_0 \\ \beta_1 \\ \beta_2 \\ \beta_3 \\ \beta_4 \\ \beta_5
\end{pmatrix} = 0
\]</span>
Esto, en R es:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="variables-indicadoras-o-dummies.html#cb17-1" aria-hidden="true" tabindex="-1"></a>L <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>),<span class="dv">1</span>,<span class="dv">6</span>,<span class="at">byrow =</span> T)</span>
<span id="cb17-2"><a href="variables-indicadoras-o-dummies.html#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(mod.UN11, <span class="at">hypothesis.matrix=</span>L)</span></code></pre></div>
<pre><code>## Linear hypothesis test
## 
## Hypothesis:
## groupother:log(ppgdp) - groupafrica:log(ppgdp) = 0
## 
## Model 1: restricted model
## Model 2: log(fertility) ~ group * log(ppgdp)
## 
##   Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
## 1    194 14.579                           
## 2    193 14.484  1  0.094808 1.2633 0.2624</code></pre>
<p>Dado que no se rechaza <span class="math inline">\(H_0\)</span>, el efecto del PNB sobre la fertilidad es el mismo para los países Africanos y los de la categoría de otros.</p>
<p>En resumen, a partir del análisis de regresión:</p>
<ul>
<li><p>El efecto del PNB per cápita sobre la fertilidad depende del tipo de país.</p></li>
<li><p>Para los países miembros de la OECD, no hay un efecto significativo.</p></li>
<li><p>Sin embaro, para los demás países, el efecto es negativo (y no es significativamente diferente para las categorías de África y otros).</p></li>
</ul>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modelos-polinomiales.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/AlvaroFlorez/MLG2/edit/master/01-Indicadoras.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/AlvaroFlorez/MLG2/blob/master/01-Indicadoras.Rmd",
"text": null
},
"download": ["MLG2.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
